### ISSUE TITLE
Move Assert-*.ps1 files into Tests\Integration Folder

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xActiveDirectory#104]
These files appear to be _manually run_ integration tests. Therefore they belong in the tests\Integration folder.

Is there any objection or reason they can't be moved?

**Comment by kwirkykat** [comment]
Yes you can move them to tests as long as they aren't used in the resources in which case these files would be moved into DSCResources. Either way they shouldn't be in the root folder as they are now.

**Comment by johlju** [comment]
Closing this as duplicate in favour of newer issue #144.
