### ISSUE TITLE
PsDscRunAsCredential is not passed to Set-ADGroup in xADGroup

### ISSUE THREAD

**Issue by stephenbonar** [PowerShell/xActiveDirectory#106]
Trying to manage an xADGroup resource using a PsDscRunAsCredential fails on certain operations. The creation of a group works, but when setting the properties of an existing group, we get "Set-ADGroup : Insufficient access rights to perform the operation". Debugging reveals that this occurs at the call to Set-ADGroup on line 387 of the MSFT_xADGroup.psm1 module. In inspecting the code, it appears that  $Credential never gets passed to the parameter list hashtable $setADGroupParams. Other calls like New-ADGroup succeed because they use a separate parameter list such as $adGroupParams which does appear to contain the credentials.

**Comment by iainbrighton** [comment]
@stephenbonar That's correct. When you use PsDscRunAsCredential, the LCM is responsible for elevating the process the resource is executed in, to run under the specified credential (and the resource knows nothing/never sees this credential).

Have you tried swapping the `PsDscRunAsCredential` to `Credential` instead? This will call the *-ADGroup cmdlets with the credential parameter.

**Comment by iainbrighton** [comment]
@stephentoub Having said that, I think you're correct in that fact that, if you do use the `Credential` parameter, it doesn't get passed to the `Set-ADGroup` cmdlet. That's a problem.

**Comment by stephenbonar** [comment]
Yeah, I wrote PsDscRunAsCredential out of habit but I really meant Credential. I went back and looked at my DSC script and I was correctly referencing Credential there.

**Comment by iainbrighton** [comment]
@stephenbonar You might have already seen, but I've submitted PR https://github.com/PowerShell/xActiveDirectory/pull/107 that should fix this. Would you mind reviewing it and seeing whether it fixes the issue?
