### ISSUE TITLE
xADUser Doesn't Lookup Alternate Domain

### ISSUE THREAD

**Issue by adweigert** [PowerShell/xActiveDirectory#11]
The DomainName attribute is not operating on a user in an alternate domain, e.g. node in TEST domain, trying to xADUser in PROD domain (PROD one way trust TEST).

Fix: Add -Server $DomainName to *-AD cmdlets.

**Comment by iainbrighton** [comment]
I'm working on implementing #44 and this should be closed off with this implementation.
