### ISSUE TITLE
get-help about_activedirectory_filter incorrect attribute

### ISSUE THREAD

**Issue by danSpotter** [PowerShell/xActiveDirectory#110]
The help references email as an AD attribute multiple times. It should be mail

**Comment by gordonbondon** [comment]
Yes, reference is wrong but about_activedirectory_filter help is not a part of DSCResource. It is a part of ActiveDirectory module help. You can probably submit feedback here https://technet.microsoft.com/en-us/library/hh531527(v=ws.10).aspx

**Comment by danSpotter** [comment]
my apologies, got some bad info on where to submit issues on powershell.
