### ISSUE TITLE
xADUser - POBox - attribute or value does not exist...

### ISSUE THREAD

**Issue by Naboo2604** [PowerShell/xActiveDirectory#115]
I try to create a new user with the xADUser and a value in the PostOffice attribute - that gives me the following error:
`The specified directory service attribute or value does not exist`
`Parameter name: POBox`

Think there is a missing property mapping in MSFT_xADUser
original:
`@{ Parameter = 'POBox'; }`

but it should be:
`@{ Parameter = 'POBox'; ADProperty = 'postOfficeBox'}`

reference: [https://msdn.microsoft.com/en-us/library/ms679367(v=vs.85).aspx](url)

br, Markus

**Comment by iainbrighton** [comment]
@Naboo2604 Oops! I'll get this fixed.

**Comment by johlju** [comment]
This was resolved in PR #49.
