### ISSUE TITLE
xADDomainController

### ISSUE THREAD

**Issue by petetakacs** [PowerShell/xActiveDirectory#119]
Deploying xADDomainController as a Azure template extension. I'm receiving the following error;
ssage: \\\"DSC Configuration 'CreateADBDC' completed with error(s). Following are the first few: Cannot bind argument to parameter 'SiteName' because it is an empty string.

In the readme.md it states that SiteName is optional which it isn't. I have adjusted the deployment script to.
		xADDomainController BDC 
        { 
            DomainName = $DomainName 
            DomainAdministratorCredential = $DomainCreds 
            SafemodeAdministratorPassword = $DomainCreds
            DatabasePath = "F:\NTDS"
            LogPath = "F:\NTDS"
            SysvolPath = "F:\SYSVOL"
			**SiteName = 'Default-First-Site-Name'**
			DependsOn = "[WindowsFeature]ADDSInstall","[xDnsServerAddress]DnsServerAddress","[cDiskNoRestart]ADDataDisk"
        }

And now it works.

**Comment by ripclawffb** [comment]
I have the same issue. This should either be fixed or the documentation needs to be updated.

**Comment by emmanuelpare** [comment]
Got the same issue here. Will investigate

**Comment by jpogran** [comment]
The root cause of the issue is here: https://github.com/puppetlabs/puppetlabs-dsc/blob/master/lib/puppet_x/dsc_resources/xActiveDirectory/DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1#L140. If ensure is set to true, then sitename is required.
