### ISSUE TITLE
After installing xActiveDirectory from PSGallery and attempting to use xADUser resource, error message appears

### ISSUE THREAD

**Issue by neil-white-iHerb** [PowerShell/xActiveDirectory#120]
The error message is:
The PowerShell DSC resource MSFT_xADUser from module <xActiveDirectory,2.13.0.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC 
resource.

I've looked in as many places as I can to try and resolve this issue on my own, including:

Removing the xActiveDirectory DSC resource and re-adding it from the PSGallery
Verified that the DSC resource is being import (i.e. Import-DSCResource -ModuleName "xActiveDirectory")
Verified that it is being installed here: C:\Program Files\WindowsPowerShell\Modules\xActiveDirectory

This is the only DSC resource I use that's having the issue.
OS: Windows Server 2012 R2
PSVersion: 5

**Comment by iainbrighton** [comment]
@neil-white-iHerb What version of the module is deployed on the target node? If you open a PowerShell prompt on the machine and run `Get-DscResource -Module xActiveDirectory` what do you get?
```powershell
PS C:\Users\Administrator> Get-DscResource -Module xActiveDirectory

ImplementedAs   Name                      ModuleName                     Version    Properties                                        
-------------   ----                      ----------                     -------    ----------                                        
PowerShell      xADComputer               xActiveDirectory               2.13.0.0   {ComputerName, DependsOn, Description, DisplayN...
PowerShell      xADDomain                 xActiveDirectory               2.13.0.0   {DomainAdministratorCredential, DomainName, Saf...
PowerShell      xADDomainController       xActiveDirectory               2.13.0.0   {DomainAdministratorCredential, DomainName, Saf...
PowerShell      xADDomainDefaultPasswo... xActiveDirectory               2.13.0.0   {DomainName, ComplexityEnabled, Credential, Dep...
PowerShell      xADDomainTrust            xActiveDirectory               2.13.0.0   {SourceDomainName, TargetDomainAdministratorCre...
PowerShell      xADGroup                  xActiveDirectory               2.13.0.0   {GroupName, Category, Credential, DependsOn...}   
PowerShell      xADOrganizationalUnit     xActiveDirectory               2.13.0.0   {Name, Path, Credential, DependsOn...}            
PowerShell      xADRecycleBin             xActiveDirectory               2.13.0.0   {EnterpriseAdministratorCredential, ForestFQDN,...
PowerShell      xADUser                   xActiveDirectory               2.13.0.0   {DomainName, UserName, CannotChangePassword, Ci...
PowerShell      xWaitForADDomain          xActiveDirectory               2.13.0.0   {DomainName, DependsOn, DomainUserCredential, P...

PS C:\Users\Administrator> 
```

**Comment by neil-white-iHerb** [comment]
The same output as you're showing on your screen there, oddly enough. I checked that as well as one of my first steps, which is why the whole issue sort of bewildered me:

![image](https://cloud.githubusercontent.com/assets/22802971/19358793/21bc5bda-912c-11e6-8698-5097c8788b54.png)

**Comment by kwirkykat** [comment]
@neil-white-iHerb Are you calling the resource 'MSFT_xADUser' in your configuration or 'xADUser'?

**Comment by neil-white-iHerb** [comment]
I'm calling the xADUser resource

**Comment by neil-white-iHerb** [comment]
Here's some example code (I'm using plain-text just for demonstration purposes):

configuration DomainConfig
{
    Import-DscResource -ModuleName "PSDesiredStateConfiguration","xHyper-V","xPSDesiredStateConfiguration","xActiveDirectory","xDnsServer","xDhcpServer"

    Node "RWDC01"
	{
		xADUser "contoso\ExampleUser"
		{
			UserName = "ExampleUser"
			Password = (New-Object System.Management.Automation.PSCredential("contoso\WMS_Dev_Biz",('Password01' | ConvertTo-SecureString -AsPlainText -Force)) )
			UserPrincipalName = "ExampleUser@contoso.com"
			DomainName = "contoso.com"
			DomainController = "RWDC01"
			PasswordNeverExpires = $true
		}
    }
}

$ConfigData = @{
    AllNodes = @(
        @{
            NodeName                    = "RWDC01"
            PSDscAllowPlainTextPassword = $True
        }
    )
}


$MOFFolderPath = "C:\DscResources"
TestDomainConfig `
-OutputPath "$MOFFolderPath" `
-ConfigurationData $ConfigData ` | Out-Null


Start-DscConfiguration -Path "$MOFFolderPath" -Credential (Get-Credential) -Wait -Verbose -Force

**Comment by neil-white-iHerb** [comment]
```
Get-DscResource -Module xActiveDirectory -Name xADUser

ImplementedAs   Name                      ModuleName                     Version    Properties                                        
-------------   ----                      ----------                     -------    ----------                                        
PowerShell      xADUser                   xActiveDirectory               2.13.0.0   {DomainName, UserName, CannotChangePassword, Ci...
```

**Comment by iainbrighton** [comment]
@neil-white-iHerb Can you post output the from that configuration? If you are running on the DC itself, can you humour me and try removing the `DomainController` and `DomainName` parameters? I'll try and the equivalent tomorrow in our lab environment.. What OS are you running this configuration on?

**Comment by neil-white-iHerb** [comment]
I'm running it on a member server. Is that okay? This is actually on a test domain, but Ops controls the domain controller. So I can't run it on the domain controller unless I want a phone call from our IT department :-).

**Comment by neil-white-iHerb** [comment]
Here is the output from the error record object (attached)

[DSCError.xml.txt](https://github.com/PowerShell/xActiveDirectory/files/537548/DSCError.xml.txt)

**Comment by PlagueHO** [comment]
Hi @neil-white-iHerb - are you able to run this command and show the output?
```powershell
Get-DscResource -Module xActiveDirectory -Name xADUser | Format-List
```

Also, when you run ```Start-DSCConfiguration```, I notice you're asking for a credential - is this credential a Domain credential and does it also have access to the c:\Program Files\WindowsPowerShell\Modules folder on this node?

I'm making the assumption that this error occurs when the config is applied, not when it is compiled - is that correct? But what may be happening is that you're compiling the config using an account on the machine that has access to xADUser, but you're starting the DSC config using a different context that doesn't have access to xADUser.

Can you make sure that the account that is being used to apply the config (the one entered when Get-Credential fires) has access to the Modules folder (make it a Local Administrator perhaps)?

**Comment by neil-white-iHerb** [comment]
Thanks for the info @PlagueHO . I'm verifying that the targets have the DSC resources installed now,

**Comment by neil-white-iHerb** [comment]
Yep. @PlagueHO   had it right. On the xHyper-V module that was working, I had forgotten I had installed the corresponding module on the Hyper-V server, so I assumed that all DSC resources (including xActiveDirectory) used a mechanism that exists in all WMF frameworks (4+). Feel a little dumb for missing something seemingly obvious. Thanks for your help guys.

**Comment by PlagueHO** [comment]
@neil-white-iHerb - no worries! Done the same thing myself many times. Glad to help.
