### ISSUE TITLE
SiteName is still required as of 2.15.0.0

### ISSUE THREAD

**Issue by Merto410** [PowerShell/xActiveDirectory#132]
Sitename is being passed as an empty string when not included instead of $Null.

Line 135 of the file MSFT_xADDomainController.psm1
Is currently:
 
if ($SiteName -ne $null) 
 
and needs to be modified to:
 
if ($SiteName -ne $null -and $Sitename -ne “”)

**Comment by Merto410** [comment]
fixed in 
[MSFT_xADDomainController.txt](https://github.com/PowerShell/xActiveDirectory/files/691124/MSFT_xADDomainController.txt)

**Comment by Merto410** [comment]
Pull request submitted with fix

**Comment by kwirkykat** [comment]
Fixed by #133
