### ISSUE TITLE
Compilation to MOF take 1.5 hours

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/xActiveDirectory#136]
This issue is reported by customer. They are generating 5500 MOFs, and it is taking 1.5 hours for the script to finish. They build the ConfigData for 5500 servers, pass that to the configuration containing approximately 100 service and registry resources, and generating the MOFs. This is triggered from a Jenkins build server on server class hardware. 

The issue is that we are generating all MOFs first in memory than writing in disk.

**Comment by kwirkykat** [comment]
@nitinbps Do you know what resource(s) from this repo they are using?

**Comment by grayzu** [comment]
Here is the original thread... not sure how to get link but in PowerShell/General Microsoft Team's channel on 11/16/2016. Summary of initial comment:
_So I've got the code and plugging through it now. Basic config. 69 resources (file, registry, service). Nothing fancy. Just 5,490 nodes. When I turn on debug output I can watch PSDesiredStateConfiguration.psm1 crank through the MOF builds. The interesting thing is that the MOF build process is entirely in memory. It does not write each MOF as it is generated. Instead, it creates all MOF files in memory and then commits them to files at the very end. I haven't gotten into the generation code yet, but these seems terribly inefficient to me. The PowerShell process goes crazy with memory consumption and CPU._

**Comment by grayzu** [comment]
I did a quick test with the following config and it took about 15 min. I did not see CPU and Memory spike, however:
$servers = for($i = 1; $i -lt 10001; $i++){"server" + $i}

Configuration Scale
{
    Node $servers
    {
        Environment SuperHero
        {
            Ensure = 'Present'
            Name = "SuperHero"
            Value = "Man of Steel"
        }

        Environment SuperHeroPower
        {
            Ensure = 'Present'
            Name = 'SuperHeroPower'
            Value = 'Strong and can fly'
        }

        Registry MySoftware
        {
            Ensure = 'Present'
            Key = 'HKLM:\SOFTWARE\SuperHeros\ManOSteel'
            ValueName = 'outfit-colors'
            ValueType = 'String'
            ValueData = 'Blue and Red'
        }
        Service SuperHeroGo
        {
            Ensure = 'Present'
            State = 'Running'
            Name = 'SuperHeroGo'
            StartupType = 'Automatic'
        }
    }
}

measure-command {Scale -OutputPath C:\Configs\mof\scale}

**Comment by nitinbps** [comment]
Filed the issue in wrong repository, hence closing it.
