### ISSUE TITLE
xADDomainController fails when site is left out

### ISSUE THREAD

**Issue by FrodeOA** [PowerShell/xActiveDirectory#140]
Hi I'm currently running a two DC server environment and according to your documentation the site parameter is optional when configuring the xADDomainController but if I leave it blank it get an error saying Install-ADDSDomainController can't continue because SiteName is empty.

Here is the configuration I'm using:

configuration AssertDC
{
   param
    (
        [Parameter(Mandatory)]
        [pscredential]$safemodeAdministratorCred,
        [Parameter(Mandatory)]
        [pscredential]$domainCred
    )

    Import-DscResource -ModuleName xActiveDirectory
    Import-DscResource –ModuleName 'PSDesiredStateConfiguration'

    Node $AllNodes.Where{$_.Role -eq "primary"}.Nodename
    {
        WindowsFeature ADDSInstall
        {
            Ensure = "Present"
            Name = "AD-Domain-Services"
        }

        WindowsFeature RSATTools 
        { 
            Ensure = 'Present'
            Name = 'RSAT-AD-Tools'
            IncludeAllSubFeature = $true
            DependsOn= '[WindowsFeature]ADDSInstall'
        }  

        xADDomain FirstDS
        {
            DomainName = $Node.DomainName
            DomainAdministratorCredential = $domainCred
            SafemodeAdministratorPassword = $safemodeAdministratorCred
            DependsOn = "[WindowsFeature]RSATTools"
        }

        xWaitForADDomain DscForestWait
        {
            DomainName = $Node.DomainName
            DomainUserCredential = $domainCred
            RetryCount = $Node.RetryCount
            RetryIntervalSec = $Node.RetryIntervalSec
            DependsOn = "[xADDomain]FirstDS"
        }
    }

    Node $AllNodes.Where{$_.Role -eq "replica"}.Nodename
    {
        WindowsFeature ADDSInstall
        {
            Ensure = "Present"
            Name = "AD-Domain-Services"
        }

        WindowsFeature RSATTools 
        { 
            Ensure = 'Present'
            Name = 'RSAT-AD-Tools'
            IncludeAllSubFeature = $true
            DependsOn= '[WindowsFeature]ADDSInstall'
        }  

        xWaitForADDomain DscForestWait
        {
            DomainName = $Node.DomainName
            DomainUserCredential = $domainCred
	    RetryCount = $Node.RetryCount
            RetryIntervalSec = $Node.RetryIntervalSec
            DependsOn = "[WindowsFeature]RSATTools"
        }
        xADDomainController SecondDC
        {
            DomainName = $Node.DomainName
            DomainAdministratorCredential = $domainCred
            SafemodeAdministratorPassword = $safemodeAdministratorCred
            SiteName = 'Default-First-Site-Name'
            DependsOn = "[xWaitForADDomain]DscForestWait"
        }
    }
}

If I comment out the SiteName in the xADDomainController SecondDC block I get the error mentioned above, if I leave it in it works fine. What's causing this, my configuration or something else?

**Comment by kwirkykat** [comment]
@FrodeOA What version of xActiveDirectory are you using? This same bug was fixed in #133 which went out in the latest version (2.16.0.0)

**Comment by FrodeOA** [comment]
I pulled down the master branch a few weeks ago and the version is 2.15.0.0 so I guess that's the issue then, thanks.
