### ISSUE TITLE
xADUser: retrieve password from Keepass and apply to xaduser

### ISSUE THREAD

**Issue by bodunjo** [PowerShell/xActiveDirectory#147]
I pre-created service accounts in Keepass as part if my SQl Install.
How do i apply the password to xaduser?

Script function to create the password in Keepass

 Script AddAgtsvcAccountKeePass
        {

             GetScript =
            {
                # Do Nothing 
                
            }

             SetScript = 
            {
            #CREATE FUNCTION FOR PASSWORD GENERATION
Function GET-Password() {
Param(
[int]$length=10,
[string[]]$sourcedata
)
For ($loop=1; $loop –le $length; $loop++) {
            $TempPassword+=($sourcedata | GET-RANDOM)
            }
return $TempPassword
}
$ascii=$NULL;For ($a=33;$a –le 126;$a++) {$ascii+=,[char][byte]$a }

$SQLagentpwdMaster = GET-Password -length 32 -sourcedata $ascii 

#Remove illegal characters from password
$ht = new-object System.Collections.Hashtable
$ht.""""=''
$ht."'"=''
$ht.'\('=''
$ht.'\)'=''
$ht.'/'=''
$ht."\\"=''
$ht.'`'=''
$ht.'\$'=''
$ht.'{'=''
$ht.'}'=''
$ht.'&'=''
$ht.'|'=''
$ht.','=''
foreach($key in $ht.Keys) { $SQLagentpwdMaster = $SQLagentpwdMaster -creplace $key, $ht.$key }

            $title = "SQL_Agent_Service_Account_" + $using:SQLserver + "_" + $using:InstanceName
           
            $count = @(C:\DBA\#KeePass#\KeePass-2.32\KPScript.exe -c:GetEntryString $using:KeePassDBPath -pw:$using:KeePassPWD  -Field:Password -username:$Using:AgtSvcAccountUsername -ref-Title:$title).Count
            #$cmdis = "$using:KeePassPath -c:AddEntry $using:KeePassDBPath -pw:$using:KeePassPWD -Title:$title -UserName:$using:AgtSvcAccountUsername -Password:sdfgsdfdf45666 -URL:http://www.domain.com/ -GroupName:SQL"
                    if($count -eq 1)
                    {                   
                  #Invoke-Expression -Command:$cmdis 
            Invoke-Command {C:\DBA\#KeePass#\KeePass-2.32\KPScript.exe -c:AddEntry $using:KeePassDBPath -pw:$using:KeePassPWD -Title:$title -UserName:$Using:AgtSvcAccountUsername -Password:$SQLagentpwdMaster -URL:http://www.domain.com/ -GroupName:SQL}
            } 
                    else
                    {
                    write-host "AddAgtsvcAccountKeePass  already exists"
                    }
                
            }

            TestScript = 
            {
            
                $false
            }
             Dependson = "[Script]SQLSvcAccountKeePass"
           
       }

--XAdUser to create the user

xADUser SQLsvcAccount
		{
			#DomainAdministratorCredential = $cred
			DomainName = $DomainName
			UserName =  $SQLSvcAccountUsername
			**Password** =  C:\DBA\#KeePass#\KeePass-2.32\KPScript.exe -c:GetEntryString "C:\DBA\#KeePass#\CT-Entrance.kdbx" -pw:KeePassPWD -Field:Password -ref-Title:"SQL_Server_Service_Account_CTDMTI01VMSQL01_KEEPASS" | select-object -first 1
			PasswordNeverExpires = $true
			Ensure = 'Present'
            Path = 'OU=Service Logons - non-compliant,OU=IT,DC=domain,DC=com'
            PsDscRunAsCredential = $PsDscRunAsCredential
            Dependson = "[xADUser]AgtsvcAccount"
            Enabled = $true
            Description = "SQLsvcAccount Service Account"
		}

**Comment by johlju** [comment]
Not sure retrieving a Password from a password manager is relevant to this resource module. Closing this issue. If this was closed in error, then please reopen or comment.
