### ISSUE TITLE
New resource for xActiveDirectory: xADSite

### ISSUE THREAD

**Issue by Hindy-UK** [PowerShell/xActiveDirectory#149]
I'd like to contribute a new resource to this module:

- xADSite - creates and manages Active Directory sites

Opening an issue before forking as per the contribution guidelines.

**Comment by solbirn** [comment]
@Hindy-UK You working on this yet or should I create?

**Comment by Hindy-UK** [comment]
hi,

I did the initial test version, but I need to update it so that it incorporates everything I've learned doing the xADSiteLink one; and add in the other optional parameters for the underlying cmdlets. I'm back on contract though and haven't got a lot of free time. I'll try and upload what I had done previously when I get a chance, but TBH xADSite and xADSubnet probably won't be too different to the xADSiteLink, which works great from pull server but fails on calling the Get-resource directly.

**Comment by solbirn** [comment]
That would be great. I started creating and then realized you may have something in progress already.

I will check that out those failures.

**Comment by jmos5156** [comment]
Hi I was wondering if I could branch from your repo for xADSite and xADSubnet?

**Comment by solbirn** [comment]
Fine by me

**Comment by X-Guardian** [comment]
@johlju, this issue can be closed as it was implemented as resource xADReplicationSite in PR #185

**Comment by johlju** [comment]
Closing this as per previous comment.
