### ISSUE TITLE
New resource for xActiveDirectory: xADSubnet

### ISSUE THREAD

**Issue by Hindy-UK** [PowerShell/xActiveDirectory#150]
I'd like to contribute a new resource to this module:

- xADSubnet - creates and manages Active Directory subnets

Opening an issue before forking as per the contribution guidelines.

**Comment by jmos5156** [comment]
Hi I was wondering if I could branch from your repo for xADSite and xADSubnet?

**Comment by johlju** [comment]
@Hindy-UK Sorry that nobody answered you for so long. Please PR in you new resource.

**Comment by X-Guardian** [comment]
@johlju, this issue can be closed as it was implemented as resource xADReplicationSubnet in PR #180

**Comment by johlju** [comment]
Closing this issue as per previous comment.
