### ISSUE TITLE
xADUser: Add ServicePrincipalNames property

### ISSUE THREAD

**Issue by Identitry** [PowerShell/xActiveDirectory#153]
Enhancement
ServicePrincipalNames property is currently only available on xADComputer but being able to set SPN using xADUser would make it easier to create and update service accounts.

**Comment by cwegener** [comment]
Looks like it should be easy to implement and it might have just been an oversight? Both, Set-ADComputer and Set-ADUser support the -ServicePrincipalNames hastable. Yet only xADComputer has implemented it as a DSC parameter.

**Comment by SSvilen** [comment]
I'll try to do it.I have a good reference with xADComputer.
