### ISSUE TITLE
New resource for Group Managed Service Accounts

### ISSUE THREAD

**Issue by Identitry** [PowerShell/xActiveDirectory#154]
Enhancement
Currently there's no way of creating Group Managed Service Accounts, that would be a great feature since this kind of accounts are being used more but currently SQL Server is where it's mainly used.

**Comment by johlju** [comment]
Do this need to be an entire new resource? Could this maybe be added to the existing xADUser resource?

**Comment by Identitry** [comment]
Yes it needs it’s own resource and there is an open pull request for a resource like this where you asked the same question.
https://github.com/PowerShell/xActiveDirectory/pull/157

**Comment by johlju** [comment]
@Identitry thank you for answering. Sorry for asking the same question twice, it's a lot of PR's and issues, and didn't remember the correlation between this and the PR. Labeling this as in progress and making sure this issue is closed when PR #157 is merged.

**Comment by johlju** [comment]
A new resource for this was recently merged.
