### ISSUE TITLE
xADDomainController: Get-DscConfiguration fails

### ISSUE THREAD

**Issue by jibinpeng** [PowerShell/xActiveDirectory#155]
The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The Ensure key is not a valid property in the corresponding DSC resource schema file. The results from Get-TargetResource 
must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC resource schema file.

**Comment by jibinpeng** [comment]
This is for xActiveDirectory version 2.16.0.0.

**Comment by alexaymonier** [comment]
Yep getting this too. Have other xActiveDirectory resources in use and this is the only one (i've seen so far). Looking in a bit deeper the return statement is returning 'ensure' which is not in the schema.mof. In the resource this is reference on line 31 and 52. Is this actually needed for the Get? If i remove the entries for 'ensure' it works fine.

**Comment by pcarnella** [comment]
Same here...other resources in the xActiveDirectory module 2.16.0.0 that I've used seem fine, just xADDomainController causing this error.

**Comment by johlju** [comment]
The ensure property is returned in the hashtable. 

https://github.com/PowerShell/xActiveDirectory/blob/4fa284e895760931ed651b8daed26c56dabac753/DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.psm1#L52

But the property does not exist in the schema.

https://github.com/PowerShell/xActiveDirectory/blob/4fa284e895760931ed651b8daed26c56dabac753/DSCResources/MSFT_xADDomainController/MSFT_xADDomainController.schema.mof#L1-L11

**Comment by JibinPeng1** [comment]
This bug exists in version 2.19.0.0 as well. Will this be fixed in the near future?

**Comment by johlju** [comment]
This work is abandoned in PR #111. Anyone in the community may continue the work, by sending in a new PR that resolves this and have a unit test that tests that this property is returned correctly (and updated the Unreleased section in the change log).
