### ISSUE TITLE
xActiveDirectory: new resource for UPN and SPN suffix management

### ISSUE THREAD

**Issue by regedit32** [PowerShell/xActiveDirectory#177]
I'd like to recommend adding a new resource to manage User Name Principal (UPN) and Service Principal Name (SPN) suffix properties in a forest.  This resource can be called xADPrincipalNameSuffix.  I have a current need for this, so I've started working on it in a fork.

**Comment by johlju** [comment]
@regedit32 There are already a resource ready to be merged that handles SPN's (see PR #163). Also xADUser already have a parameter `UserPrincipalName`, so if something is missing in that resource, maybe we could extend that instead? Or is it necessary creating a separate resource for handling UPN's?

**Comment by johlju** [comment]
@regedit32 Maybe I missunderstood. Are you proposing a resource that adds an alternative UPN suffix,
 like mentioned in the article [Add User Principal Name Suffixes](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc772007(v=ws.11)?

**Comment by regedit32** [comment]
@johlju Yes, exactly like that article. The same can be done for Service Principal Name suffixes for a forest.

**Comment by johlju** [comment]
@regedit32 Ah good, then I understand the new resource proposal. Would you mind posting the schema.mof you are proposing? Then it can be discussed if needed. 😄

**Comment by regedit32** [comment]
@johlju Sounds good, here's the link to the mof I'm working on.  I should have the tests done shortly. https://github.com/regedit32/xActiveDirectory/blob/xADPrincipalNameSuffix/DSCResources/MSFT_xADPrincipalNameSuffix/MSFT_xADPrincipalNameSuffix.schema.mof

**Comment by johlju** [comment]
@regedit32 Just a thought. What if we named this xADForest or xADForestProperties so we could get more properties of a forest in the resource than adding a new resource for each property? Just looking ahead if we one day stand with 10+ resources for different properties, maybe we should see if we can concatenate those today already.  Just raising a thought, what do you think? Are there more properties on top of these that could fit into a "xADForest..." resource?

**Comment by regedit32** [comment]
@johlju I like the name xADForestProperties.  I'm not sure what other properties we would support in the future.  The Set-ADForest cmdlet is pretty limited and those are the only two properties available to change with that.

**Comment by johlju** [comment]
Sorry that I haven't reviewed or commented on this. Been busy with the day job. :/

If we rename it to xADForestProperties then if there were to come more properties then we probably could get those properties in to this resource if it was named xADForestProperties. If we keep the name, we would need to rename it (breaking change) or create another resource.
My personal opinion is that we should rename the resource to xADForestProperties .
