### ISSUE TITLE
xADGroup Applying MembersToInclude also changes GroupScope when not specified 

### ISSUE THREAD

**Issue by mvaneijken** [PowerShell/xActiveDirectory#183]
xADGroup is changing the GroupScope of a Universal group to a Global group  when using the following settings:

 GroupName = "Group"
 MembersToInclude = $UserName
 MembershipAttribute = "SamAccountName"

Shouldn't it only add the member specified instead of changing other attributes of this group?

**Comment by johlju** [comment]
This happens because the default value is set to 'Global'. The resource should not change a value that is not part of a configuration.

https://github.com/PowerShell/xActiveDirectory/blob/4fa284e895760931ed651b8daed26c56dabac753/DSCResources/MSFT_xADGroup/MSFT_xADGroup.psm1#L280

**Comment by johlju** [comment]
This was resolved in PR #197.
