### ISSUE TITLE
Windows Server 2016 forest functional level features

### ISSUE THREAD

**Issue by leegh123** [PowerShell/xActiveDirectory#187]
when i config ad with dsc, how can i set the forest functional level features to windows server 2008 R2?

**Comment by leegh123** [comment]
i have done it

**Comment by leegh123** [comment]
i add DomainMode, ForestMode  two parameters to the MSFT_xADDomain.psm1 file and change the MSFT_xADDomain.schema.mof too,now it is ok .

**Comment by johlju** [comment]
@leegh123 Can you describe what changes you did to the schema.mof?

**Comment by leegh123** [comment]
in the schema.mof file i add two lines 
[Write, Description("set domain mode")] String DomainMode;
[Write, Description("Set Forest Mode")] String ForestMode;

**Comment by johlju** [comment]
@leegh123 Thanks for the information! Let's keep this issue open and I labeled it as an enhancement. Would you be interested in sending in a PR with this change? 

I think we should use a `[ValidateSet()]` with the appropriate values the user can choose.

**Comment by nyanhp** [comment]
Hi @johlju , I had the same problem at a customer of mine, extended the resource and quickly forgot about submitting the changes... Since there is no reaction from @leegh123 , I will go ahead and submit a pull request ~tomorrow after I have added some tests for the added functionality if that's ok.

**Comment by johlju** [comment]
@nyanhp Sounds great. Please send a PR.

**Comment by sakhatri** [comment]
Do we have a timeline when to expect this feature to be available as a part of master branch?

**Comment by johlju** [comment]
@sakhatri nest community call is set for the 18th so approximately a week after that there will be new releases for resource modules in DSC Resource Kit.
