### ISSUE TITLE
Pester test not passing

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShell/xActiveDirectory#19]
xActiveDirectory\DSCResorce\MSFT_xADRecycleBin\Test\ResorceDesigner.Tests.ps1
fails

Describing xADRecycleBin
   Context xDscResouceDesigner
    [-] Pass Test-xDscResource 355ms
      The term 'Test-xDscResource' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
      at line: 7 in H:\GitHub\xActiveDirectory\DSCResources\MSFT_xADRecycleBin\Tests\ResourceDesigner.Tests.ps1
    [-] Pass Test-xDscSchema 232ms
      The term 'Test-xDscSchema' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
      at line: 12 in H:\GitHub\xActiveDirectory\DSCResources\MSFT_xADRecycleBin\Tests\ResourceDesigner.Tests.ps1

**Comment by KarolKaczmarek** [comment]
Hi @BladeFireLight 
Do you have DscResourceDesigner installed? https://github.com/powershell/xdscresourcedesigner

I just run tests on both master and dev branches and they pass.

**Comment by tysonjhayes** [comment]
#31 removed these tests so I think this isn't an issue anymore.
