### ISSUE TITLE
Should there be xADReplicationSiteLink Resource?

### ISSUE THREAD

**Issue by ryanspletzer** [PowerShell/xActiveDirectory#191]
Hi folks. This may be due to my own ignorance, but as I was browsing the module I didn't see any resource for manage AD Site Links. And I didn't see any reference in the code or issues elsewhere about it so I thought I'd post something so it's at least out here for other curious people like me.

Is there a reason why there does not currently exist an xADReplicationSiteLink resource? Perhaps some technical limitation in AD that prevented this from being effectively managed from PowerShell DSC?

Any insight is appreciated. :) If this is something people maybe wanted I could perhaps work on a PR with a new resource for this. :) Thanks!

**Comment by johlju** [comment]
There seems to be a PowerShell cmdlet for that [New-ADReplicationSiteLink](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adreplicationsitelink?view=winserver2012-ps).

Most likely nobody in the community has ran with it again. 
Are you seeing this as a new resource or could this be added to an existing resource? If you see this as a new resource, please propose a schema.mof an post it here. 

You are very welcome to send in a PR. Look over [Contribution](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md) for more information.

**Comment by ryanspletzer** [comment]
Yes I should have been more specific: I didn't see any DSC resource in this module for managing AD Site Links. :) Did know about the Get/New/Remove/Set-ADReplicationSiteLink cmdlets.

I think this could be a new resource, let me see if I can get around to a proposed schema.mof and perhaps a PR, too. Thanks!
