### ISSUE TITLE
Duplication of code in example in readme.md

### ISSUE THREAD

**Issue by AspenForester** [PowerShell/xActiveDirectory#198]
In the first example, asserting a highly available domain, the entire block of code intended for the example has been pasted in twice.

**Comment by AspenForester** [comment]
Likewise, the code for configuration AssertParentChildDomains shows up again at the end of the next example.

**Comment by johlju** [comment]
Label this as help wanted so that anyone in the community can run with this.

**Comment by johlju** [comment]
Re-opening this as there is still a duplicate of AssertParentChildDomains.

**Comment by thequietman44** [comment]
I created a new pull request with the duplicate AssertParentChildDomains removed.
