### ISSUE TITLE
Add xADRecycleBin to xActiveDirectory

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/xActiveDirectory#2]
I have written a MOF-based resource to enable the AD recycle bin.

**Comment by GoateePFE** [comment]
Per the guidelines I "transfer full ownership of xADRecycleBin to the PowerShell organization".

**Comment by vors** [comment]
Thank you @GoateePFE ! Transfer of ownership is applicable to the whole repository (). In this case, you are contributing one resource to existing repository. Does it make sense?

**Comment by GoateePFE** [comment]
Yes. Thank you.

**Comment by vors** [comment]
Fixed per #6 and #5
