### ISSUE TITLE
Version 2.4 in the PSGallery dropped properties on xADDomain

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/xActiveDirectory#21]
xActiveDirectory version 2.4 in the PSGallery dropped properties on xADDomain:
DatabasePath
LogPath
Must add these back to the latest version.

**Comment by GoateePFE** [comment]
Please replace xADDomain resource in 2.4 with code from 2.3.

**Comment by KarolKaczmarek** [comment]
Fixed by #9
