### ISSUE TITLE
"Unable to find a default server with Active Directory Web Services running" when running test

### ISSUE THREAD

**Issue by shurick81** [PowerShell/xActiveDirectory#213]
### Steps to reproduce
1. Install windows 2016 server
2. Install AD module:

```PowerShell
            PSModule "PSModule_xActiveDirectory"
            {
                Ensure              = "Present"
                Name                = "xActiveDirectory"
                Repository          = "PSGallery"
                InstallationPolicy  = "Trusted"
                RequiredVersion     = "2.19.0.0"
            }
```
3. Install "AD-Domain-Services"
4. Start configuration with domain:

```PowerShell
            xADDomain ADDomain
            {
                DomainName                      = $domainName
                SafemodeAdministratorPassword   = $domainSafeModeAdministratorPasswordCredential
                DomainAdministratorCredential   = $shortDomainAdminCredential
            }
```
5. Start configuration with user account:

```PowerShell
            xADUser SPInstallAccountUser
            {
                DomainName              = $domainName
                UserName                = $SPInstallAccountCredential.GetNetworkCredential().UserName
                Password                = $SPInstallAccountCredential
                PasswordNeverExpires    = $true
            }
```
6. Test the configuration using `Test-DscConfiguration`.

### Expected result
true returned

### Actual outcome
An error,
```
    AD01: VERBOSE: [AD01]: LCM:  [ Start  Resource ]  [[xADUser]SPFarmAccountUser]
    AD01: VERBOSE: [AD01]: LCM:  [ Start  Test     ]  [[xADUser]SPFarmAccountUser]
    AD01: VERBOSE: [AD01]:                            [[xADUser]SPFarmAccountUser] Retrieving Active Directory user '_sp
frm16'
    AD01: (_spfrm16@contoso.local) ...
    AD01: VERBOSE: [AD01]: LCM:  [ End    Test     ]  [[xADUser]SPFarmAccountUser]  in 0.0320 seconds.
    AD01: VERBOSE: [AD01]: LCM:  [ End    Set      ]
    AD01: VERBOSE: Operation 'Invoke CimMethod' complete.
    AD01: VERBOSE: Time taken for configuration job to complete is 1.214 seconds
    AD01: Error looking up Active Directory user '_spadm16' (_spadm16@contoso.local).
    AD01:     + CategoryInfo          : NotSpecified: (:) [], CimException
    AD01:     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-TargetResource
    AD01:     + PSComputerName        : AD01
    AD01: PowerShell DSC resource MSFT_xADUser  failed to execute Test-TargetResource functionality with error message:
Unable
    AD01: to find a default server with Active Directory Web Services running.
    AD01:     + CategoryInfo          : InvalidOperation: (:) [], CimException
    AD01:     + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    AD01:     + PSComputerName        : AD01
```

### Additional information
When I test the very same sequence in Windows 2012 R2 it works, but in 2016 it throws an error, even though `Start-DscConfiguration` successfully creates the account.

**Comment by johlju** [comment]
Does it fail on `Get-DscConfiguration` as well? It looks like it fails in the `Get-TargetResource` that `Test TargetResource` fails. If so it must be `Get-ADUser` that fails?

**Comment by shurick81** [comment]
Hi, I found that the resource works fine when I use normal user session. So the issue only happens when I provision via Vagrant. It can be probably related to privilege elevation.

**Comment by shurick81** [comment]
I think I managed to solve it now. The thing is that my scenario is
1. create domain
2. restart the machine
3. add accounts
It seems that It was machine restart and then trying to run the script too early. So what I had to do is adding this waiting resource:

```
            xWaitForADDomain WaitForDomain
            {
                DomainName              = $domainName
                DomainUserCredential    = $ShortDomainAdminCredential
                RetryCount              = 100
                RetryIntervalSec        = 10
            }

            xADUser SPInstallAccountUser
            {
                DomainName              = $domainName
                UserName                = $SPInstallAccountCredential.GetNetworkCredential().UserName
                Password                = $SPInstallAccountCredential
                PasswordNeverExpires    = $true
                DependsOn               = "[xWaitForADDomain]WaitForDomain"
            }
```

10 x 100 gave me 1000 seconds of waiting and it can depend on your hardware performance and resource allocation of course. In my VM running on the average laptop and Windows allocated with 1024MB RAM and 2 virtual CPUs it took just 280 seconds, so 1000 must be more than enough.

**Comment by shurick81** [comment]
One can actually find useful some best practices for this coupling of resources. I mean it can be a best practice: before applying any domain customizations it won't hurt to run the xWaitForADDomain and set DependsOn. What do you think @johlju?

**Comment by johlju** [comment]
If the same configuration installs the AD, it can't be assumed the AD is running, so I think there should be a xWaitForADDomain resource in the those configurations. If the a configuration can assume there will always be an AD then there should be no need. But it won't hurt having it, probably will just add a few more seconds when running the script.
