### ISSUE TITLE
xADGroup members does not support Computer Objects

### ISSUE THREAD

**Issue by r00nster** [PowerShell/xActiveDirectory#220]
The "MembersToInclude" property (and I suspect "Members" & "MembersToExclude" properties) only support AD Group and AD User account types. If the property contains an AD Computer account the following errors are displayed.

"_The specified local group already exists_"

"_The PowerShell DSC resource [xADgroup]<ResourceName> with SourceInfo <scriptpath> threw a non-terminating errors while running the Set-TargetResource functionality._"

The first error is incorrect and seems to be a 'generic' error  displayed with most errors in this DSCResource

**Comment by johlju** [comment]
@r00nster Could you please provide the configuration that generates the problem, and the verbose logs where the problem occur.

**Comment by iainbrighton** [comment]
@r00nster You are specifying the computer names ending with a $, e.g. `COMPUTERNAME$`?

**Comment by r00nster** [comment]
"School Boy" error!! 

for the $ on the end of the computernames as iainbrigton stated above.

Been a long week....

**Comment by johlju** [comment]
@r00nster Think I did the same mistake a while back 😄 Glad you got it solved.
