### ISSUE TITLE
Error creating new domain with xADDomain with 2.20.00

### ISSUE THREAD

**Issue by MayPLaY** [PowerShell/xActiveDirectory#221]
Hi,

With 2.20.0.0, since this introduction :
> xADDomain is now capable of setting the forest and domain functional level

LCM is giving me `"PowerShell DSC resource MSFT_xADDomain  failed to execute Test-TargetResource functionality with error message: Unable to find type [Microsoft.DirectoryServices.Deployment.Types.ForestMode]. "` after rebooting when creating a forest/domain. 

The problem happens with or without `ForestMode` parameter.

LCM's error :
[problem_2.20.0.0.log](https://github.com/PowerShell/xActiveDirectory/files/2264673/problem_2.20.0.0.log)

Thanks.

**Comment by johlju** [comment]
It seems the type that was introduced with that change does not exist on a AD server, see issue #218. Since this is already being tracked in issue #218 I'm closing this as a duplicate.
