### ISSUE TITLE
xADDomainController issue after deployment

### ISSUE THREAD

**Issue by Blankf** [PowerShell/xActiveDirectory#222]
i've installed my new dc (2016 Core) with xADDomainController and the installation completed, server rebooted and i have myself a new domain controller.
Replication seems fine and domain seems fine, so far so good.

But with a new dsc-configuration run it fails with the following error: The specified argument 'ConfirmGc' was not recognized.

so i checked the code of the resource, and saw that Install-ADDSDomainControllerInstallation was used, so tested that manually but gave the same error.

Also when running Test-ADDSDomainControllerInstallation gives the following error: The specified argument 'ConfirmGc' was not recognized.

```
Message                                                                                                                        Context                                                 RebootRequired  Status
-------                                                                                                                        -------                                                 --------------  ------
Test VerifyAdminTrustedForDelegation completed successfully                                                                    Test.VerifyAdminTrustedForDelegation.DCPromo.General.1           False Success
Test VerifyADPrepPrerequisites completed successfully                                                                          Test.VerifyADPrepPrerequisites.ADPrep.General.0                  False Success
Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGc' was not recognized... Test.VerifyDcPromoCore.DCPromo.General.77                        False   Error
Test VerifyOutboundReplicationEnabled completed successfully                                                                   Test.VerifyOutboundReplicationEnabled.DCPromo.General.1          False Success
```

i have integrated with an 2008R2 Domain/forest.

**Comment by johlju** [comment]
I'm not following you. Are you running `Test-ADDSDomainControllerInstallation` in a PowerShell console on the new Windows Server 2016 that you want to promote to a domain controller? 
Are you trying to install a second domain controller and join the same domain as the first domain controller that was successfully installed?

Can you provide the verbose logs where you get the error, and the configuration you are using. Obfuscate any sensitive information.

**Comment by Blankf** [comment]
so after the first dsc configuration the machine is promoted to a dc, then the second run fails with the error `The specified argument 'ConfirmGc' was not recognized.`

Then investigating i tried indeed `Test-ADDSDomainControllerInstallation` and it gives the same result.

Then i had a look at the code and tried the `Install-ADDSDomainController @params` and got the same result 

`Install-ADDSDomainController -DomainName 'xxxx' -SafeModeAdministratorPassword $Secure_String_Pwd -Debug

The target server will be configured as a domain controller and restarted when this operation is complete.
Do you want to continue with this operation?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y

Confirm
Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGc' was not
recognized.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
Install-ADDSDomainController : Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGc' was not recognized.
At line:1 char:1
+ Install-ADDSDomainController -DomainName 'xxxxx' -SafeModeAdministrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-ADDSDomainController], TestFailedException
    + FullyQualifiedErrorId : Test.VerifyDcPromoCore.DCPromo.General.77,Microsoft.DirectoryServices.Deployment.PowerShell.Commands.InstallADDSDomainControllerCommand

Message                                                                                                                        Context                                   RebootRequired Status
-------                                                                                                                        -------                                   -------------- ------
Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGc' was not recognized... Test.VerifyDcPromoCore.DCPromo.General.77          False  Error`

this was the third dc, the others are 2008R2 domaincontroller already ( for a long time ) these new 2016 ones should replace those in the near future.

**Comment by johlju** [comment]
You are right that this isn't the DSC resource. Since you making a jump from 2008 R2 to 2016 I would recommend you talk to Microsoft Support to get a migration path and so they can help you make sure the environment is stable for migration.
