### ISSUE TITLE
xADDomainController fails with user cred

### ISSUE THREAD

**Issue by riponbanik** [PowerShell/xActiveDirectory#228]
ISSUE TITLE:
    xADDomainController fails with user cred

    ISSUE DESCRIPTION (this template):

   Using template like this below -

    xADDomainController ReplicaDC  {
          DomainName = $DomainDnsName          
          DomainAdministratorCredential = $DomainAdministratorCredentials
          SafemodeAdministratorPassword = $SafeModeCredentials
          DatabasePath = 'C:\NTDS'
          LogPath = 'C:\NTDS' 
          DependsOn = "[xWaitForADDomain]DscForestWait"
        }
     
    It fails with the following error - 

"Verification of user credential permissions failed. The wizard cannot access the list of domains in the forest. The error is:\r\nA specified logon session does not exist. It may already have been terminated.\r\n The PowerShell DSC resource '[xADDomainController]DirectResourceAccess' with SourceInfo '' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational

#### Details of the scenario you tried and the problem that is occurring
Added Primary Domain Controller with DSC and now wants to add replica DC.

#### Verbose logs showing the problem
"Verification of user credential permissions failed. The wizard cannot access the list of domains in the forest. The error is:\r\nA specified logon session does not exist. It may already have been terminated.\r\n The PowerShell DSC resource '[xADDomainController]DirectResourceAccess' with SourceInfo '' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 xADDomainController ReplicaDC  {
          DomainName = $DomainDnsName          
          DomainAdministratorCredential = $DomainAdministratorCredentials
          SafemodeAdministratorPassword = $SafeModeCredentials
          DatabasePath = 'C:\NTDS'
          LogPath = 'C:\NTDS' 
          DependsOn = "[xWaitForADDomain]DscForestWait"
        }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19125.amd64fre.winblue_ltsb.180812-0703
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
latest

**Comment by johlju** [comment]
Could you please provide the verbose logs showing the error? Run `Start-DscConfiguration -Path <path_to_mof_folder> -Wait -Verbose`. Obfuscate any sensitive information.

**Comment by riponbanik** [comment]
I have resolved the issue. I needed to provide user name as user@domain.
