### ISSUE TITLE
Unable to compile PowerShell DSC script to deploy a ADForest

### ISSUE THREAD

**Issue by ameyaagashe** [PowerShell/xActiveDirectory#231]
Hi there
[CreateADForest.zip](https://github.com/PowerShell/xActiveDirectory/files/2440604/CreateADForest.zip)

Please find attached PowerShell DSC script to deploy an AD Forest along with input parameters.

I am unable to understand the error message below:
`**Credential with name 'HashDollar135' not found for account '49437a73-d126-4e50-bd1f-5a4fd460665f'**.`

I would sincerely appreciate any help offered.

Many thanks
Ameya Agashe

**Comment by johlju** [comment]
Looks like you are deploying this from within Azure Automation? Did you create a Credential in Azure Automation, and referencing that credential name?

**Comment by ameyaagashe** [comment]
@johlju Yes, I did, the screenshot in the attached zip file.

Please let me know if you have any questions.

Thanks and Regards,
Ameya Agashe

**Comment by ameyaagashe** [comment]
@johlju Any update mate?

**Comment by johlju** [comment]
@ameyaagashe Just to make sure we are talking about the same thing. Before you wrote the credential name in the credential parameter field of the configuration compilation, did you add the credential object to the Credential blade? See credential in the below screen shot - it looks like on the error message that it doesn't find a credential object here?

![image](https://user-images.githubusercontent.com/7189721/46572263-1bda7300-c983-11e8-9114-d788db9d2b87.png)

**Comment by ameyaagashe** [comment]
@johlju I get the same error even after adding the credentials..

[Unable to compile PowerShellSC script to deploy a ADForest.docx](https://github.com/PowerShell/xActiveDirectory/files/2454478/Unable.to.compile.PowerShellSC.script.to.deploy.a.ADForest.docx)

What I am not clear and do apologize if I sound silly as I am very new to this, is, I have been challenged to enter the credentials to the variable defined in the script (Step 2) in the attached word document so why we are adding them again in Asset(Credentials)?

Anyway, I did add them in Credentials but still get the same error, please refer to the attached word document (Step 4).

Doing wrong anywhere, anything? I am still unable to understand what is the exact issue?

Many Thanks
Ameya Agashe

**Comment by johlju** [comment]
In the parameter fields you should use the same name that is visible under the name file under Credentials, 'AdminCreds', etc. Azure Automation should automatically pick up the credential object then.

**Comment by ameyaagashe** [comment]
Unfortunately, it's not happening so what is the next step for resolution?

**Comment by johlju** [comment]
@ameyaagashe Sorry to hear that it's not working for you. Unfortunately I'm not seeing this as a problem with the resources in this resource module, but instead you are having an issue using Azure Automation. This is an issue that is outside of the scope of these resources.
Please look at https://docs.microsoft.com/en-us/azure/automation/automation-dsc-compile, or other articles around compiling configurations in Azure Automation, and see if it helps.
