### ISSUE TITLE
Combine DscResource.LocalizationHelper and DscResource.Common into xActiveDirectory.Common

### ISSUE THREAD

**Issue by johlju** [PowerShell/xActiveDirectory#268]
We should combine the helper modules DscResource.LocalizationHelper and DscResource.Common into xActiveDirectory.Common.

We need to name the new module xActiveDirectory.Common so it does not conflict with another resource modules helper module if both resource modules would be using the same generic name.
That could result in missing helper functions if both moduels are used in the same configuration.

**Comment by SSvilen** [comment]
Hi,

So basically what needs to happen here is to merge the code from both modules into a new module and then update all script module files and all pester test files(are they called like that or just unit test files?), where the the old modules are referenced(imported)?

**Comment by SSvilen** [comment]
I made an attempt to combine them and I've create a PR. Let's see how that goes..
One question though - do I need to do some sort of testing on my machine first? Or is only the CI pipeline used for that part?

**Comment by devopsjesus** [comment]
Combining the modules like that will require some forklifting in the unit tests as well, as those are part of what is validated during the pipeline.
