### ISSUE TITLE
xADDomain creates domain but no longer passes test-target resource

### ISSUE THREAD

**Issue by BladeFireLight** [PowerShell/xActiveDirectory#27]
after the reboot folowing a sucsessfuly configuration the first domcain contoler no longer works and DSC failes to complete.

VERBOSE: [DC01]: LCM:  [ Start  Resource ]  [[xADDomain]FirstDC]
VERBOSE: [DC01]: LCM:  [ Start  Test     ]  [[xADDomain]FirstDC]
VERBOSE: [DC01]:                            [[xADDomain]FirstDC] Resolving 'Contoso.com' ...
VERBOSE: [DC01]:                            [[xADDomain]FirstDC] Current node is not running AD WS, and hence is not a
domain controller.
VERBOSE: [DC01]: LCM:  [ End    Test     ]  [[xADDomain]FirstDC]  in 0.6420 seconds.
VERBOSE: [DC01]: LCM:  [ Start  Set      ]  [[xADDomain]FirstDC]
VERBOSE: [DC01]:                            [[xADDomain]FirstDC] Checking if domain 'Contoso.com' is present ...
VERBOSE: [DC01]:                            [[xADDomain]FirstDC] Verified that domain 'Contoso.com' is not already
present, continuing ...
VERBOSE: [DC01]:                            [[xADDomain]FirstDC] Domain 'Contoso.com' is NOT present. Creating forest
'Contoso.com' ...
VERBOSE: [DC01]:                            [[xADDomain]FirstDC] Created forest 'Contoso.com'.
VERBOSE: [DC01]: LCM:  [ End    Set      ]  [[xADDomain]FirstDC]  in 0.2660 seconds.
The PowerShell DSC resource MSFT_xADDomain threw one or more non-terminating errors while running the
Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational.
Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

PS C:\PSTemp> Trace-xDscOperation | where eventtype -eq error | fl

EventType    : ERROR
TimeCreated  : 7/28/2015 7:56:32 PM
Message      : This event indicates that failure happens when LCM is processing the configuration. ErrorId is 0x1.
               ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [xADDomain]FirstDC
               and SourceInfo is G:\PKIBuild\DC01_Config.ps1::104::9::xADDomain. ErrorMessage is The PowerShell DSC
               resource MSFT_xADDomain threw one or more non-terminating errors while running the Set-TargetResource
               functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational.
               Refer to this channel for more details..
ComputerName : DC01
JobID        : 6981f11f-359d-11e5-80cd-00155d23709f
SequenceID   : 1
Event        : System.Diagnostics.Eventing.Reader.EventLogRecord

EventType    : ERROR
TimeCreated  : 7/28/2015 7:56:32 PM
Message      : This event indicates that a non-terminating error was thrown when DSCEngine was executing
               Set-TargetResource on MSFT_xADDomain DSC resource. FullyQualifiedErrorId is Test.VerifyDcPromoCore.DCPro
               mo.General.77,Microsoft.DirectoryServices.Deployment.PowerShell.Commands.InstallADDSForestCommand.
               ErrorMessage is Verification of prerequisites for Domain Controller promotion failed. The specified
               argument 'DataBasePath' was not recognized.
               .
ComputerName : DC01
JobID        : 6981f11f-359d-11e5-80cd-00155d23709f
SequenceID   : 1
Event        : System.Diagnostics.Eventing.Reader.EventLogRecord

EventType    : ERROR
TimeCreated  : 7/28/2015 7:56:32 PM
Message      : DSC Engine Error :
                    Error Message The SendConfigurationApply function did not succeed.
                   Error Code : 1
ComputerName : DC01
JobID        : 6981f11f-359d-11e5-80cd-00155d23709f
SequenceID   : 1
Event        : System.Diagnostics.Eventing.Reader.EventLogRecord

**Comment by iainbrighton** [comment]
+1. I see this issue with v2.5.0.0 of the resource. Looking back through my configs, it looks like it was working with v2.2.. I will try some more testing.

**Comment by tcsatheesh** [comment]
+1 I also see this issue with v2.5.0.0 of the resource.

**Comment by anwather** [comment]
Can you please provide more information on the adminCred and how you resolved the issue.

**Comment by 1RedOne** [comment]
I've got the same problem.  DC Promo, prereqs, etc all work, then we get the identical failure on Test-DSCResource.  I bet there is a problem w/ Test-DSCResource.  Seems like the newest wave of Resources have a LOT of test problems.

**Comment by 1RedOne** [comment]
I would suggest that we Omit the domain administrator credential used here.  If you run the cmdlet of Get-ADDomain -DomainName $DomainName on it's own, that will always work.  The issue is that incorrect creds (which is the real issue here, not the absence of AD WS on a Domain Controller) is incorrectly caught as 'Invalid Credentials'

**Comment by iainbrighton** [comment]
I had this issue but it turned out to be mismatched passwords. This was what was happening:

* the local Administrator password on the DC (before promotion) was different to the password/credential used in the resource.
* When the domain was created, the local administrator password remained the same as it was before the promotion.
* When the Test-TargetResource pass ran, it was using the incorrect password, said the domain wasn't available and tried to create it.

Can you confirm the local administrator password is the same as the password used in the xADDomain resource? If so, I still think it needs to be resolved if possible and if not, the documentation updated stating this very clearly!

**Comment by 1RedOne** [comment]
When I specified the same credential I used before, the test passed, so you're right on the money, Ian.

**Comment by CtrlDot** [comment]
I'm not completely sure this is a problem with this particular lib, but I thought I would post it here.

I have installed the xActiveDirectory V2.8.0.0 via the PSGallery to Azure Automation.  

Relevant code:
        xADDomain FirstDS{
            DomainName = $Node.domainName
            DomainAdministratorCredential = $domainCredential
            SafemodeAdministratorPassword = $domainCredential
            LogPath = $Node.logPath
            DatabasePath = $Node.databasePath
            SysvolPath = $Node.sysvolPath
            DependsOn = "[File]NTDSFolder","[File]DatabaseFolder","[File]SysvolFolder"
        }

Here is the error message that I see:  

PS C:\Users\shamir> Start-DscConfiguration -UseExisting -Force -Wait
Verification of prerequisites for Domain Controller promotion failed. The specified argument 'DataBasePath' was not
recognized.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Test.VerifyDcPromoCore.DCPromo.General.77,Microsoft.DirectoryServices.Deployment.PowerSh
   ell.Commands.InstallADDSForestCommand
    + PSComputerName        : localhost

I took a quick look at the code but couldn't spot any problems.  Not sure if others are experiencing this.

**Comment by oradcliffe** [comment]
I'm getting this issue when applying DSC to an Azure RM template, relevant DSC stuff is here: 

`configuration CreateFirstDC
{ 
   param 
   ( 
        [Parameter(Mandatory)]
        [String]$DomainName,

        [Parameter(Mandatory)]
        [System.Management.Automation.PSCredential]$Admincreds,

        [Int]$RetryCount=20,
        [Int]$RetryIntervalSec=30
    ) 
    
    Import-DscResource -ModuleName xActiveDirectory, xNetworking, xPendingReboot
    [System.Management.Automation.PSCredential ]$DomainCreds = New-Object System.Management.Automation.PSCredential ("${DomainName}\$($Admincreds.UserName)", $Admincreds.Password)

    Node localhost
    {
        LocalConfigurationManager            
        {            
            ActionAfterReboot = 'ContinueConfiguration'            
            ConfigurationMode = 'ApplyAndAutoCorrect'            
            RebootNodeIfNeeded = $true            
        } 

        WindowsFeature DNS 
        { 
            Ensure = "Present" 
            Name = "DNS"
        }

        xDnsServerAddress DnsServerAddress 
        { 
            Address        = '127.0.0.1' 
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            DependsOn = "[WindowsFeature]DNS"
        }

        WindowsFeature ADDSInstall 
        { 
            Ensure = "Present" 
            Name = "AD-Domain-Services"
        }  

        xADDomain FirstDS 
        {
            DomainName = $DomainName
            DomainAdministratorCredential = $DomainCreds
            SafemodeAdministratorPassword = $DomainCreds
            DependsOn = "[WindowsFeature]ADDSInstall","[xDnsServerAddress]DnsServerAddress"
        }

        WindowsFeature ADDSTools            
        {
            Ensure = "Present"
            Name = "RSAT-ADDS"
            DependsOn = "[WindowsFeature]ADDSInstall"          
        }

        xWaitForADDomain DscForestWait
        {
            DomainName = $DomainName
            DomainUserCredential = $DomainCreds
            RetryCount = $RetryCount
            RetryIntervalSec = $RetryIntervalSec
            DependsOn = "[xADDomain]FirstDS"
        }

        xPendingReboot Reboot1
        { 
            Name = "RebootServer"
            DependsOn = "[xWaitForADDomain]DscForestWait"
        }
   }
} `

The error I am getting back now, after a lot of trial and error, is that the domain cannot be reached so set-targetresource isn't working.  

"New-AzureRmResourceGroupDeployment : 2:43:28 PM - VM has reported a failure when processing extension
'Microsoft.Powershell.DSC'. Error message: "DSC Configuration 'CreateFirstDC' completed with error(s). Following are
the first few: PowerShell DSC resource MSFT_xWaitForADDomain  failed to execute Set-TargetResource functionality with
error message: Domain 'gametimeor.priv' NOT found after 20 attempts.  The SendConfigurationApply function did not
succeed.".

These are the same credentials that are being passed to initially set up the server, so I don't think that mismatched passwords is the issue; aside from that I can also log into the machine after dcpromo with domain\adminuser credentials, where before the domain is created I use .\adminuser with the same password.

Any ideas?

**Comment by oradcliffe** [comment]
Additionally, do I even need to do a wait?  Could I skip using this module all together?  From the DSC event logs it looks like almost as soon as it realizes it needs a reboot for dcpromo, it does so, even without the wait for domain.  I am guessing if I was going to add a second or third machine to the domain I would need to wait for it?
