### ISSUE TITLE
xADReplicationSiteLink: Test-TargetResource threw one or more non-terminating errors when creating

### ISSUE THREAD

**Issue by powertim** [PowerShell/xActiveDirectory#294]
ISSUE DESCRIPTION:

#### Details of the scenario you tried and the problem that is occurring

When trying to create a new AD Site Replication Link (Ensure = Present), the test which should detect that the desired replication link doesn't exist, throws an error.

#### Verbose logs showing the problem
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SRV001 with user sid
S-1-5-21-1956757076-549936234-913568690-4580.
VERBOSE: [SRV001]: LCM:  [ Start  Set      ]
VERBOSE: [SRV001]: LCM:  [ Start  Resource ]  [[xADReplicationSiteLink]tim]
VERBOSE: [SRV001]: LCM:  [ Start  Test     ]  [[xADReplicationSiteLink]tim]
Cannot find an object with identity: 'test-link' under: 'CN=Inter-Site
Transports,CN=Sites,CN=Configuration,DC=contoso,DC=test,DC=priv'.
    + CategoryInfo          : ObjectNotFound: (test-link:) [], CimException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,M
   icrosoft.ActiveDirectory.Management.Commands.GetADReplicationSiteLink
    + PSComputerName        : localhost

VERBOSE: [SRV001]:                            [[xADReplicationSiteLink]tim] Could not find test-link site link.
VERBOSE: [SRV001]: LCM:  [ End    Test     ]  [[xADReplicationSiteLink]tim]  in 0.0160 seconds.
The PowerShell DSC resource '[xADReplicationSiteLink]tim' with SourceInfo
'C:\Users\tim\Documents\test.ps1::7::9::xADReplicationSiteLink' threw one or more non-terminating errors while
running the Test-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

VERBOSE: [SRV001]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.168 seconds
```

#### Suggested solution to the issue
Catch this error as this is expected (as the replication doesn't exist yet)
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
configuration Example_xADReplicationSite
{
    Import-DscResource -Module xActiveDirectory

    Node localhost
    {
        xADReplicationSiteLink 'tim'
        {
           Ensure = 'Present'
           Name   = 'test-link'
	   Description = 'test tim'
           ReplicationFrequencyInMinutes = 15
           SitesIncluded = 'TEST, tim'
        }
    }
}

Example_xADReplicationSite

Start-DscConfiguration -Path .\Example_xADReplicationSite -Wait -Verbose -Force
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2068.amd64fre.rs1_release.180209-1727
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.14393.2068
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2068
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used: 
2.26.0.0 from PSGallery

**Comment by johlju** [comment]
It seems it was assumed that the `Get-ADReplicationSiteLink` handles like other cmdlets and supports the `-ErrorAction 'SilentlyContinue'`, but it seems few ActiveDirectory cmdlets does this.

https://github.com/PowerShell/xActiveDirectory/blob/58d8dfa9c4818a741552447ec85b6ce1f11102fd/DSCResources/MSFT_xADReplicationSiteLink/MSFT_xADReplicationSiteLink.psm1#L34-L36

It should instead use the pattern

https://github.com/PowerShell/xActiveDirectory/blob/58d8dfa9c4818a741552447ec85b6ce1f11102fd/DSCResources/MSFT_xADComputer/MSFT_xADComputer.psm1#L231-L240

**Comment by powertim** [comment]
Hi,

Yes that the problem with terminating errors and non-terminating errors.
I remember that the Get-ADObject returns null when the requested object doesn't exist.
Do you know when the fix will be available ?

Thanks for your help.

Tim.

**Comment by johlju** [comment]
This should be an “easy” fix for someone in the community. The code and tests should be able to be copied from xADComputer I think, so I labeled this “good first issue”. 

Anyone in the community may send in a fix for this. I’m happy to review a PR once sent in. :smile:

**Comment by johlju** [comment]
This is being worked on in PR https://github.com/PowerShell/xActiveDirectory/pull/304.
