### ISSUE TITLE
xADReplicationSubnet: System.UnauthorizedAccessException when creating new subnet (working without any errors with PS cmdlet)

### ISSUE THREAD

**Issue by powertim** [PowerShell/xActiveDirectory#297]
#### Details of the scenario you tried and the problem that is occurring
When trying to create a new AD Subnet (Ensure = Present), the creation of the subnet fails with an "Acces is denied" message. It's working correctly with the New-ADReplicationSubnet cmdlet and same account.
#### Verbose logs showing the problem
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SRV001 with user sid
S-1-5-21-1981357076-679936276-913568690-1209.
VERBOSE: [SRV001]: LCM:  [ Start  Set      ]
VERBOSE: [SRV001]: LCM:  [ Start  Resource ]  [[xADReplicationSubnet]tim]
VERBOSE: [SRV001]: LCM:  [ Start  Test     ]  [[xADReplicationSubnet]tim]
VERBOSE: [SRV001]: LCM:  [ End    Test     ]  [[xADReplicationSubnet]tim]  in 0.5930 seconds.
VERBOSE: [SRV001]: LCM:  [ Start  Set      ]  [[xADReplicationSubnet]tim]
VERBOSE: [SRV001]:                            [[xADReplicationSubnet]tim] Create the replication subnet test-subnet
Access is denied
    + CategoryInfo          : PermissionDenied: (CN=test-subnet,...test,DC=priv:) [], CimException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.UnauthorizedAccessException,Microsoft.ActiveDirectory.Manag
   ement.Commands.NewADReplicationSubnet
    + PSComputerName        : localhost

VERBOSE: [SRV001]:                            [[xADReplicationSubnet]tim] Set on replication subnet test-subnet the
 site to tim
Cannot validate argument on parameter 'Identity'. The argument is null. Provide a valid value for the argument, and
then try running the command again.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.SetADRepl
   icationSubnet
    + PSComputerName        : localhost

VERBOSE: [SRV001]: LCM:  [ End    Set      ]  [[xADReplicationSubnet]tim]  in 0.2500 seconds.
The PowerShell DSC resource '[xADReplicationSubnet]tim' with SourceInfo
'C:\Users\tim\Documents\test1.ps1::7::9::xADReplicationSubnet' threw one or more non-terminating errors while
running the Set-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

VERBOSE: [SRV001]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.308 seconds
```
#### Suggested solution to the issue
No idea...
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
configuration Example_xADReplicationSubnet
{
    Import-DscResource -Module xActiveDirectory

    Node localhost
    {
        xADReplicationSubnet 'tim'
        {
           Ensure = 'Present'
           Name   = 'test-subnet'
	       Site= "tim"
	       Location= "tim"
        }
    }
}

Example_xADReplicationSubnet

Start-DscConfiguration -Path .\Example_xADReplicationSubnet -Wait -Verbose -Force
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2068.amd64fre.rs1_release.180209-1727
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.14393.2068
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2068
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.26.0.0 from PSGallery

**Comment by johlju** [comment]
My guess is that because configuration runs as SYSTEM, and that account probably don't have access to AD you get permission denied. Could you try to add `PsDscRunAsCredential` to the configuration?
https://docs.microsoft.com/en-us/powershell/dsc/configurations/runasuser

**Comment by powertim** [comment]
> My guess is that because configuration runs as SYSTEM and that account probably don't have access to AD you get permission denied. Could you try to add `PsDscRunAsCredential` to the configuration?
> https://docs.microsoft.com/en-us/powershell/dsc/configurations/runasuser

Yeah it's true I was not aware of that...
Sorry for the false positive.

Have a nice day,

Tim.
