### ISSUE TITLE
xADOrganizationalUnit: Test-TargetResource threw one or more non-terminating errors when creating OU

### ISSUE THREAD

**Issue by powertim** [PowerShell/xActiveDirectory#298]
#### Details of the scenario you tried and the problem that is occurring
When trying to create a new AD Organizational Unit (Ensure = Present), the test which should detect that the desired OU doesn't exist, throws an error.
#### Verbose logs showing the problem
```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SRV001 with user sid
S-1-5-21-1956757076-549936234-913568690-4580.
VERBOSE: [SRV001]: LCM:  [ Start  Set      ]
VERBOSE: [SRV001]: LCM:  [ Start  Resource ]  [[xADOrganizationalUnit]tim]
VERBOSE: [SRV001]: LCM:  [ Start  Test     ]  [[xADOrganizationalUnit]tim]
VERBOSE: [SRV001]:                            [[xADOrganizationalUnit]tim] Retrieving OU 'tim'.
Directory object not found
    + CategoryInfo          : ObjectNotFound: (:) [], CimException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:Microsoft.ActiveDirectory.Management.ADIdentityNotFoundException,M
   icrosoft.ActiveDirectory.Management.Commands.GetADOrganizationalUnit
    + PSComputerName        : localhost

VERBOSE: [SRV001]:                            [[xADOrganizationalUnit]tim] OU 'tim' does not exist when it should
exist.
VERBOSE: [SRV001]: LCM:  [ End    Test     ]  [[xADOrganizationalUnit]tim]  in 0.0470 seconds.
The PowerShell DSC resource '[xADOrganizationalUnit]tim' with SourceInfo
'C:\Users\tim\Documents\test2.ps1::7::9::xADOrganizationalUnit' threw one or more non-terminating errors while
running the Test-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

VERBOSE: [SRV001]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.204 seconds
```
#### Suggested solution to the issue
Catch this error as this is expected (as the replication doesn't exist yet)
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
configuration Example_xADOrganizationalUnit
{
    Import-DscResource -Module xActiveDirectory

    Node localhost
    {
        xADOrganizationalUnit 'tim'
        {
           Ensure = 'Present'
           Name   = 'tim'
           Path = "OU=tim,OU=Sites,DC=contoso,DC=test,DC=priv"
           Description = "tim - Specific Containers for AD objects"
        }
    }
}

Example_xADOrganizationalUnit

Start-DscConfiguration -Path .\Example_xADOrganizationalUnit -Wait -Verbose -Force
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2068.amd64fre.rs1_release.180209-1727
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.14393.2068
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2068
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.26.0.0 from PSGallery

**Comment by iainbrighton** [comment]
Hi @powertim I think it's failing because you are trying to create an OU called `\Sites\tim\tim` and the parent path `\Sites\tim` does not exist (the target name is not part of the path). I think you need to update your config to:
```powershell
configuration Example_xADOrganizationalUnit
{
    Import-DscResource -Module xActiveDirectory

    Node localhost
    {
        xADOrganizationalUnit 'tim'
        {
           Ensure = 'Present'
           Name   = 'tim'
           Path = "OU=Sites,DC=gvt,DC=icrctest,DC=priv"
           Description = "tim - Specific Containers for AD objects"
        }
    }
}
```
This of course assuming that the root `Sites` OU exists too 😉.

**Comment by powertim** [comment]
Oh my bad...
I used a wrong example.
So yes, with the correct path it's ok for this step, but now I have a strange System.UnauthorizedAccessException like I have in #297...
New-ADOrganizationalUnit cmdlet working as expected with the same account.

**Comment by johlju** [comment]
See https://github.com/PowerShell/xActiveDirectory/issues/297#issuecomment-497228043.

Since the initial question was resolved I closing this issue.
