### ISSUE TITLE
Domain join fails on reboot 

### ISSUE THREAD

**Issue by kenazk** [PowerShell/xActiveDirectory#30]
After the DC promo + reboot, the configuration does a TEST of all the resources. This ends up failing on my xWaitForADDomain resource because it can't find the domain after 10 minutes. Note, this is post domain join (2nd reboot) -- so I don't know why it can't find the domain after the reboot. 

VERBOSE: [2015-08-27T03:01:46] [ERROR] PowerShell DSC resource MSFT_xWaitForADDomain  failed to execute Set-TargetResource 
functionality with error message: Domain 'sphafarm.com' NOT found after 20 attempts.

**Comment by aarsan** [comment]
+1

**Comment by scottzilla** [comment]
+1

**Comment by xtophs** [comment]
See my response in https://github.com/Azure/azure-quickstart-templates/issues/557#issuecomment-137604041

A different configuration for the LCM fixed it for me.

**Comment by TravisEz13** [comment]
@kenazk Could this be a dupe of Issue #32 ?

**Comment by kenazk** [comment]
This was due to a bug in WMF that has been fixed in the DSC 2.6 version. Please use that one.

**Comment by oradcliffe** [comment]
So I am having this issue as well, using `RebootNodeIfNeeded = $true` using `xWaitForADDomain`.  This is a domain controller that is joined to the domain, and I am passing the same credentials that are passed as local administrator.
