### ISSUE TITLE
xADRecycleBin: Need to remove ShouldProcess from code

### ISSUE THREAD

**Issue by johlju** [PowerShell/xActiveDirectory#328]
This resource is using a non-supported function. Best practices are to not use ShouldProcess in DSC resources since DSC does not support that interactive function.

**Comment by kungfu71186** [comment]
This looks like there is no Ensure parameter. @johlju Would you agree to just remove the shouldprocess binding and add in ensure to enable/disable?

**Comment by johlju** [comment]
This can only be enabled or disabled per forest, so I don't see the need to an `Ensure` parameter. `Ensure` parameter is normally used when removing and adding objects. This is just a existing property that can only have two states, enabled or disabled. 🤔

**Comment by kungfu71186** [comment]
Right, i forgot once it's enabled, you can no longer disable it. I guess just removing the shouldprocess would be sufficient enough.

**Comment by johlju** [comment]
Yes that is sufficient :) Are you working on this one now?

**Comment by kungfu71186** [comment]
Maybe, I don't want to commit to it quite yet. I'll finish up a few things and see if I have time. It just depends on how long my other commitments take. For now, I'll keep it open for someone to grab if they wish.

**Comment by kungfu71186** [comment]
Will wait until #330 is merged to work on this one.

**Comment by johlju** [comment]
@kungfu71186 I will run with this one.
