### ISSUE TITLE
Add xADGroup Resource

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xActiveDirectory#33]
We could do with a resource for creating AD Groups - or more importantly controlling/enforcing group membership.

**Comment by iainbrighton** [comment]
I'm not sure how this will integrate with pull request #20. The default 'Group' resource will create/remove local groups as well as set membership. I think it's better to split the logic into two resources? Thoughts?

**Comment by iainbrighton** [comment]
I have a first pass at a xADGroup resource here: https://github.com/iainbrighton/xActiveDirectory with Pester test coverage. It doesn't implement group memberships as there's an outstanding pull request. Would you like me to send a pull request for this?

**Comment by KarolKaczmarek** [comment]
@HemantMahawar , @GoateePFE - can you take a look?

**Comment by HemantMahawar** [comment]
I had an in-person chat with @iainbrighton  at PowerShell Summit Europe 2015 to understand the outstanding pull request #20 and this pull request. It would be best to merge these 2 resources to have an ability to create ADGroup and its members ... just like the built-in local group resource.

@GoateePFE and @MGreenegit ... do you agree?

**Comment by iainbrighton** [comment]
@KarolKaczmarek @HemantMahawar there's been no update on this? Are you happy for me to send a pull request for https://github.com/iainbrighton/xActiveDirectory ? I can look at merging in the Group membership functionality from #20 with a similar syntax to the local User resource?

**Comment by HemantMahawar** [comment]
@iainbrighton @KarolKaczmarek  @GoateePFE and @MGreenegit... Yes, Ian go ahead with that.

**Comment by iainbrighton** [comment]
@KarolKaczmarek @GoateePFE @MGreenegit @KarolKaczmarek - Pull request submitted. Once merged I'll get to work on adding the Members, MembersToInclude and MembersToExclude functionality.
