### ISSUE TITLE
xActiveDirectory: Remove xActiveDirectory_TechNetDocumentation.html

### ISSUE THREAD

**Issue by johlju** [PowerShell/xActiveDirectory#344]
The following file is obsolete and should be removed;
https://github.com/PowerShell/xActiveDirectory/blob/dev/xActiveDirectory_TechNetDocumentation.html

*Personally I do not see it containing any relevant information.*

**Comment by JamesFrierson1** [comment]
added #362 . I was unsure how much of the task list I needed to complete. Please let me know if there's more I can do!

**Comment by johlju** [comment]
@JamesFrierson1 For that PR (change) the change log entry was enough! Please continue sending in PR's. 😃

**Comment by JamesFrierson1** [comment]
Thanks, @johlju !
