### ISSUE TITLE
Add the ability to create forest without installing local DNS server

### ISSUE THREAD

**Issue by dovreshef** [PowerShell/xActiveDirectory#38]
Please externalize the InstallDns parameter on Install-ADDSForest to xADDomain. 
We usually build AD without DNS server role.

**Comment by iainbrighton** [comment]
@dovreshef It's been raised by @TravisEz13 that if we externalise the -InstallDns parameter that we actually need to manage the DNS role state (see #60). Just throwing this out there; can you not use the `WindowsFeature` resource to with `Ensure = 'Absent'` to remove the DNS role when/if installed by the `xADDomain` resource?

**Comment by TravisEz13** [comment]
@iainbrighton Assuming that the dcpromo simply installs the feature, managing it with WindowsFeature should work.  But to actually know, I think someone would have to try it.

**Comment by dovreshef** [comment]
@iainbrighton I don't think it is workable. Considering the resource will be converged every half an hour or so, it seems woefully inefficient to install the DNS only to remove it immediately. Also, since that windows server is supposed to be connected to a BIND server we'll have to keep restoring the setting again & again.

**Comment by TravisEz13** [comment]
@dovreshef My proposal was to model it in the xADDomain resource with the following property:
[Write, 
    ValueMap{"Present", "Absent", "NoChange"},
    Values{"Present", "Absent", "NoChange"}, 
    Description("Specifies the DNS Server service state for this machine")] 
    String EnsureDns;

This would allow you to describe a state, that you can test for, and get the machine to the state.  
Here is a table of the EnsureDns property and relavent states and what I think the resource could do.  I don't think eveything has to be implemented in the first go.  
```
***************************************************************************************
|                           | Present         | Absent              | NoChange        |
***************************************************************************************
| Nothing Installed         | install w/ dns  | Install w/o DNS     | choose a default|
***************************************************************************************
| AD w/ DNS                 | do nothing      | remove DNS          | do nothing      |
***************************************************************************************
| AD w/o DNS                | Install DNS     | Do nothing          |  do nothing     |
***************************************************************************************
```

**Comment by dovreshef** [comment]
@TravisEz13 That would be great for my use case.

**Comment by TravisEz13** [comment]
@iainbrighton @PlagueHO Do you have any comments on the above design proposal?

**Comment by PlagueHO** [comment]
I'm thinking the "choose a default" would "do nothing" as well and would need to detect the current state of the DNS and promote the DC accordingly.

Also, as this is an optional parameter, I would think that the if the parameter was not provided in the Config it would default to "Present". That way existing configs will still work just fine and install the DNS server as expected.

But it all looks good! Thanks @TravisEz13

**Comment by HemantMahawar** [comment]
@TravisEz13 @PlagueHO  @iainbrighton  Is there a reason to make the DNS property on this resource a tri-state when the default in underlying cmdlets is $true? - https://technet.microsoft.com/en-us/library/hh974720.aspx. cc .. @grayzu @nanalakshmanan

**Comment by TravisEz13** [comment]
@HemantMahawar There should be a state that you do not what to change this, if it is an explicit try state, on a tri-state via a nullable parameter with two explicit value.  There are cases, where you do not explicitly care about the state of this option and should be able to not affect it.  I think it is clearer to have a tri-state validate set, but it could also be model this way, which is technially a tri-state:

```
_______________________________________________________________________________________
|                           | Present         | Absent              | Null            |
_______________________________________________________________________________________
| Nothing Installed         | install w/ dns  | Install w/o DNS     | choose a default|
_______________________________________________________________________________________
| AD w/ DNS                 | do nothing      | remove DNS          | do nothing      |
_______________________________________________________________________________________
| AD w/o DNS                | Install DNS     | Do nothing          |  do nothing     |
_______________________________________________________________________________________
```

**Comment by TravisEz13** [comment]
@PlagueHO I agree not specifying the parameter would be the equivalent of 'NoChange", but I believe this should be an option.  I've gotten feedback from people that it is confusing when `$null` means something explicit that cannot be specified any other way.

**Comment by PlagueHO** [comment]
@TravisEz13  - I think not specifying the EnsureDNS parameter in a config should be the same as setting it to "Present", because most configs are not going to specify this parameter and you want them to keep on working as expected.

E.g.
```
_______________________________________________________________________________________
|                           | Present/Not Set | Absent              | NoChange        |
_______________________________________________________________________________________
| Nothing Installed         | install w/ DNS  | Install w/o DNS     | install /w DNS  |
_______________________________________________________________________________________
| AD w/ DNS                 | do nothing      | remove DNS          | do nothing      |
_______________________________________________________________________________________
| AD w/o DNS                | Install DNS     | Do nothing          |  do nothing     |
_______________________________________________________________________________________
```

**Comment by TravisEz13** [comment]
@PlagueHO I think the default depends on the most common use case.  Do you think we need the no change option, or can it be eliminated?

**Comment by PlagueHO** [comment]
@TravisEz13 - the most common use case would be to always install DNS with AD, so that is presumably how most people using the resource have got it set currently. @iainbrighton ?

Ideally the EnsureDNS parameter would only be used in a config when you specifically don't want DNS on an DC or it has already been promoted with DNS and you now want to get rid of it for what ever reason.

I don't actually think we need the NoChange option.

**Comment by iainbrighton** [comment]
@PlagueHO @TravisEz13 @HemantMahawar My concern is that you can (and probably should) use the WindowsFeature resource if you don't want DNS installed. You could quite easily create a configuration that keeps installing/uninstalling the role as two resources could now implement the same functionality!

__In hind sight, it would probably have been better if the xADDomain had never installed the DNS role.__ The DNS role could then be exclusively controlled via the WindowsFeature resource, installing it before promoting to a DC. Unfortunately, the default behaviour is to install DNS unless instructed otherwise. Doing it this way would be a breaking change though..

**Comment by PlagueHO** [comment]
@iainbrighton - I understand now (a bit of a doh moment).

So this option is essentially a "I want to manage DNS using WindowsFeature".

This option is definitely required.

In this case I think the table should be:
```
_______________________________________________________________________________________
|                           | Present/Not Set | Absent              | NoChange        |
_______________________________________________________________________________________
| Nothing Installed         | install w/ DNS  | install w/o DNS     | install w/o DNS |
_______________________________________________________________________________________
| AD w/ DNS                 | do nothing      | remove DNS          | do nothing      |
_______________________________________________________________________________________
| AD w/o DNS                | install DNS     | do nothing          | do nothing      |
_______________________________________________________________________________________
```

That way any existing configs won't break.

**Comment by TravisEz13** [comment]
@dovreshef I have twitter contact information in my profile.  could you contact me?  I'd like to understand more about your scenario.

**Comment by TravisEz13** [comment]
@dovreshef Can you describe the scenario you want this for?  I don't think the direction in this issue will work for us?  I need to understand what you are trying to do.  The most likely  case we can think of is that you want to create a child domain (or a second controller in an existing domain) without DNS server.

**Comment by dovreshef** [comment]
@TravisEz13 Sorry for being out of touch. 
What we were trying to do is add active directory to an application that runs primarily on Linux and its DNS is managed by BIND.  
We have gone back to using PowerShell scripts (called from Chef) to manage it for now, so I'm ok with closing this.

**Comment by TravisEz13** [comment]
@dovreshef My suggestion, close this issue and reopen one saying "Add the ability to create forest using existing BIND DNS server"  Is that closer to your scenario?

**Comment by iainbrighton** [comment]
@TravisEz13 Does @PlagueHO still need this functionality (or close to it)?

**Comment by PlagueHO** [comment]
@PlagueHO, lets close it I think. The new "Add the ability to create forest using existing BIND DNS server" would cover my scenarios too:
"Add the ability to create forest using existing Microsoft DNS server"

**Comment by TravisEz13** [comment]
I filed issue #87.  Closing this issue

**Comment by dovreshef** [comment]
@TravisEz13 Thanks!
