### ISSUE TITLE
xActiveDirectory: Resource have a requirements section (in wiki README.md)

### ISSUE THREAD

**Issue by johlju** [PowerShell/xActiveDirectory#394]
The resource xADComputer have a _Requirements_ section in the README.md that is used to generate the wiki documentation. See here https://github.com/PowerShell/xActiveDirectory/blob/dev/DSCResources/MSFT_xADComputer/README.md

I suggest we add this section to the other resources README.md as well. The *Requirements*  section is meant to list requirements for a resource, for example if the resource or a specific property can only be used on node with Windows Server 2016 and above, or AD of a specific flavor or specific configuration.

**Comment by JamesFrierson1** [comment]
Hi @johlju I'd be happy to contribute! Just to be clear, are you interested in adding the Requirements section that states "Target machine must be running Windows Server 2008 R2 or later" to every README.md in the DSCResources folder?

**Comment by johlju** [comment]
You are very welcome to contribute this! Yes, we can add that if it is true. It is probably is true in most, right? :thinking: If you know any more requirements please add them, otherwise other PRs can complement the sections later. If you add the section without any requirements for a resource then we probably should write ‘None.’ :thinking:

I think it most important that the section exist so that it is clear it just not the description that can go in that README.md

**Comment by johlju** [comment]
@JamesFrierson1 I just tried the new "read-only assignee" functionality. If you decide that you don't have time to contribute this, just un-assign yourself from this issue. But looking forward to a PR. Thank you!

**Comment by JamesFrierson1** [comment]
Sounds good, @johlju . I created PR #399 and added the Requirements section as we discussed. I went ahead and stated very DSCResource requires Windows Server 2008 R2 or later, but if that isn't true I can go back and just write "None" like you suggested

**Comment by johlju** [comment]
@JamesFrierson1 it is probably true, if it is not for one resource, I think we let another PR resolve that. 🙂
