### ISSUE TITLE
Add RODC Creation Support

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xActiveDirectory#40]
Is there any plan to add support to install a server as an RODC?

**Comment by oradcliffe** [comment]
Commenting here as I am also curious if this will be supported.  Otherwise, I guess using a custom script block in the DSC template will do?

**Comment by capocruz** [comment]
nope, doesn't look like it...

**Comment by SSvilen** [comment]
Hi @johlju  - is this still relevant?

**Comment by johlju** [comment]
@SSvilen If someone want to add this then I'm all for it, happy to review a PR that adds this. 🙂

**Comment by SSvilen** [comment]
I need to pre-provision the RODC account and then i need to promote it. Do I pick up a single domain controller to work with for both operations or is there another standard for such operations?

**Comment by johlju** [comment]
The cmdlet [`Add-ADDSReadOnlyDomainControllerAccount`](https://docs.microsoft.com/en-us/powershell/module/addsdeployment/add-addsreadonlydomaincontrolleraccount?view=win10-ps) can only specify the domain name and site name, so you could create the account on any DC and it should replicate, and it must of course have replicated before promoting the RODC. You can also specify the replication source DC if the RODC should replicate from a specific domain controller, so the account must have replicated to that DC before promoting.

**Comment by johlju** [comment]
Not sure we should have a resource that creates that pre-staged account, should we? It is one-time thing, and nothing that can be enforced, and needs to be done by a domain admin. I think to solve this issue I think we just need to support the parameter `ReadOnlyReplica` in the resource xADDomainController (for the cmdlet `Install-ADDSDomainController`).

**Comment by SSvilen** [comment]
You are right - you can provision RODC with Install-ADDSDomainController directly. But we could also build the functionality to pre-provision the account, couldn't we? I would still a part of xADDomainController - just a separate set of options.

**Comment by johlju** [comment]
Creating a pre-staged (computer) account sounds more something xADComputer would do, not xADDomainController. Or another (new) resources.

But what node should create the prestige account? It wouldn’t be the node that will end up as RODC, because then it wouldn’t make since to use a pre-stage account in the first place. The node that should be RODC should be using xADDomainControlle with `ReadOnlyReplica` and an optional Credential that allows the DC to use the already created pre-staged account. 

It’s not really making since to me to create the pre-staged account using a DSC resource. :thinking:

**Comment by jojiklmts** [comment]
2019. Where is my RODC provisioned with PowerShell DSC?

**Comment by johlju** [comment]
@jojiklmts sorry, not following you. But if you mean the support for RODC it has been merged and will be included in the release of ActiveDirectoryDsc (which hopefully be soon).
