### ISSUE TITLE
xActiveDirectory: CI pipeline failed to release examples

### ISSUE THREAD

**Issue by johlju** [PowerShell/xActiveDirectory#409]
During the latest release the CI pipeline failed to release the examples with the error `InvalidGuid`. The problem is probably an invalid GUID in one or more script file info at the top of the examples.

```
[Build Info] [UTC 06/26/2019 21:59:17] Found API key to use for publishing to the PowerShell Gallery.
[Build Info] [UTC 06/26/2019 21:59:17] Evaluating examples that end with 'Config' if they need publishing.
InvalidGuid,Test-ScriptFileInfo
```

https://ci.appveyor.com/project/PowerShell/xActiveDirectory/branch/master?fullLog=true#L4394

**Comment by johlju** [comment]
When the wrong GUID is found we should add an issue to the test framework (DscResource.Tests) to add a common test for this.

**Comment by X-Guardian** [comment]
Not a very helpful message! Suggest we add some verbose messaging into the `Test-PublishMetadata` function in `DSCResource.Tests\DscResource.GalleryDeploy\DscResource.GalleryDeploy.psm1`

The first problem is with example `xADComputer\3-AddComputerAccountSpecificPath_Config.ps1` where `Test-ScriptFileInfo` reports the GUID being invalid. It is missing a character from the first set in the GUID.

Interestingly, `Test-PublishMetadata` is also reporting issues with two other examples:

```
WARNING: Skipping publishing example '\xActiveDirectory\Examples\Resources\xADObjectEnabledState\2-CreateClusterComputerAccount_Config.ps1'.
The example could not be read, for example if there is a required module missing when the script should be parsed, or general script parsing errors.
General errors should have been caught with the common example validation test. 


WARNING: Skipping publishing example '\xActiveDirectory\Examples\Resources\xADObjectEnabledState\3-EnabledPrestagedClusterComputerAccount_Config.ps1'.
The example could not be read, for example if there is a required module missing when the script should be parsed, or general script parsing errors.
General errors should have been caught with the common example validation test.
```

These both contains an additional `xFailoverCluster` resource, which I assume is the problem.

**Comment by johlju** [comment]
The example script needs to be able to be parsed for the Test-PublishMetadata to work, but I think the publish functionality is making sure the module exist in the build worked, or maybe it is just the common test that make sure the module exist so the common test can compile the examples.

**Comment by X-Guardian** [comment]
Looking at the current `Common Tests - Validate Example Files To Be Published` tests, only duplicate GUIDs are checked, not whether they are valid. This would be easy to add. It is also currently ignoring any errors from `Test-ScriptFileInfo` which could be changed.

**Comment by X-Guardian** [comment]
I used `Test-ScriptFileInfo` on `xADObjectEnabledState\2-CreateClusterComputerAccount_Config.ps1` and it does produce the parse error if any of the referenced modules are not installed. Should we have examples that reference other modules?

**Comment by johlju** [comment]
The test framework will install any additional modules on the build worker that are needed to compile the examples.

**Comment by johlju** [comment]
> Looking at the current Common Tests - Validate Example Files To Be Published tests, only duplicate GUIDs are checked, not whether they are valid. This would be easy to add. It is also currently ignoring any errors from Test-ScriptFileInfo which could be changed.

I add a issue for that in DscResource.Tests.

**Comment by johlju** [comment]
Oh that was already done! Awesome! 😄

**Comment by johlju** [comment]
I'm closing this as I think @X-Guardian has resolved everything. 😄 Next release should publish the examples correctly. Maybe we eventhe module has been renamed so they are released with the new names without 'x'.
