### ISSUE TITLE
Property NewDomainNetBiosName not found

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xActiveDirectory#45]
Running the resource xADDomain currently returns this error:

 > A parameter cannot be found that matches parameter name 'NewDomainNetbiosName'.

Looking in to this I found that [there was a change made](https://github.com/PowerShell/xActiveDirectory/commit/4b07ffba205419c545ab6d76a800f8fb11fb6333) which changed the property from DomainNetbiosName to NewDomainNetbiosName. This appears to have caused the issue, looking at this on Windows Server 2012 R2 there is no property called NewDomainNetbiosName, just the old DomainNetbiosName. I'm happy to make the change to fix this but I'm curious to know why the change went in to begin with. Also looking at [the documentation for Server 2012 and 2012 R2](https://technet.microsoft.com/en-us/library/hh974720%28v=wps.630%29.aspx) neither of them have "new" at the start of the parameter name either.

@dougbrw - are you able to shed some light on where you saw this invalid parameter?

**Comment by dougbrw** [comment]
Hey,

It looks like this is a mistake and those parameters need to be reverted for "Install-ADDSForest". The parameters for "Install-ADDSDomain" were wrong as you can see here https://technet.microsoft.com/en-us/library/hh974722(v=wps.630).aspx it does have a parameter named "NewDomainNetbiosName", but I seem to have changed it in both places. I don't have an environment to test this in at the moment but rolling back the change on line 134 should fix the issue.

Many thanks,
Doug

**Comment by BrianFarnhill** [comment]
I tested it on an environment today and changed it back worked fine, I'll roll it back and put in the pull request. Thanks Doug!

**Comment by dougbrw** [comment]
I noticed there is a pull request which fixes "Install-ADDSForest" but breaks "Install-ADDSDomain" again: https://github.com/PowerShell/xActiveDirectory/pull/42

I will link that thread to this issue to prevent us from going around in circles. If you are creating a new domain & forest then you end up using "Install-ADDSForest" but if you are creating a child domain then you end up using "Install-ADDSDomain", so most scenarios people probably use and test 50% of this resource.

**Comment by BrianFarnhill** [comment]
Good call doug - the fix that will work for both is in my PR #45 and that's the one we should move forward with.

**Comment by 1RedOne** [comment]
Hi Doug,

Do you have a link to your commit with this fix?  This issue is biting me today but I don't see where to make the change you recommended.

Thanks

Stephen

**Comment by BrianFarnhill** [comment]
For anyone else looking at the fix, its at #46 :)
