### ISSUE TITLE
xWaitForADDomain does not validate prerequisite of ActiveDirectory module

### ISSUE THREAD

**Issue by SimonWahlin** [PowerShell/xActiveDirectory#47]
The resource xWaitForADDomain is typically run on a member server or a client.
The resource uses Get-ADDomain which isn't available on either by default.

Any error thrown by Get-ADDomain results in a message stating:
"Domain $DomainName not found. Will retry again after $RetryIntervalSec sec"

The resource should have a requirement of the module ActiveDirectory, or if the error is "The term 'Get-ADDomain' is not recognized as the name of a cmdlet, function, script file, or operable program" this should be reflected in the output.

**Comment by iainbrighton** [comment]
And that's why I wrote https://github.com/iainbrighton/cWaitForTcpPort ! In v5.0 you can use the DSC WaitFor resources.

In answer to that actual problem, this is almost identical to #32 and should be addressed at the same time?

**Comment by iainbrighton** [comment]
@SimonWahlin PR #63 resolves this and the AD module is no longer required! Can you confirm that this is resolved?

**Comment by SimonWahlin** [comment]
Nice work! Looks good to me, thanks!

**Comment by iainbrighton** [comment]
@SimonWahlin Can this now be closed?

**Comment by SimonWahlin** [comment]
Yes, I consider this solvef
