### ISSUE TITLE
New Commits not being updated in powershellgallery?

### ISSUE THREAD

**Issue by prateekjain0608** [PowerShell/xActiveDirectory#50]
The latest commits in the Module are not being updated when we download using the powershell command 
Install-Module -Name xActiveDirectory
The commit 
https://github.com/PowerShell/xActiveDirectory/commit/2b2f142076750b2b19a013e7fb8cccace7341e6a

was not updated when!

**Comment by iainbrighton** [comment]
@prateekjain0608 Only the published releases are pushed to the PSGallery. Therefore, until the dev branch is merged, it won't appear in the gallery. If you want to pull the development branch you can refer to: http://blogs.msdn.com/b/powershell/archive/2015/08/27/development-builds-for-dsc-resources-are-available.aspx.

@KarolKaczmarek I think this issue can be closed?

**Comment by iainbrighton** [comment]
This commit should now be in the PSGallery. @KarolKaczmarek @TravisEz13 I think this can be closed?
