### ISSUE TITLE
xADDomain - check for domain existence returns wrong error message

### ISSUE THREAD

**Issue by simongdavies** [PowerShell/xActiveDirectory#53]
Check for domain existence in https://github.com/PowerShell/xActiveDirectory/blob/2b2f142076750b2b19a013e7fb8cccace7341e6a/DSCResources/MSFT_xADDomain/MSFT_xADDomain.psm1#l42 returns incorrect error messages. 

For example if I pass invalid domain credentials it will fail with ***Current node is not running AD WS, and hence is not a domain controller.***

**Comment by iainbrighton** [comment]
@simongdavies this should have be fixed in PR #60. Can you confirm whether the changes fix this?

**Comment by iainbrighton** [comment]
@TravisEz13 I think this can now be closed?

**Comment by TravisEz13** [comment]
@simongdavies Please re-open if this still occurs with the lastest module.
