### ISSUE TITLE
Resource for AD Delegation of Control

### ISSUE THREAD

**Issue by Sjark** [PowerShell/xActiveDirectory#57]
I would like a resource to be able to Delegate Control in Active Directory to Users and Groups.

You should be able with DSC to set Active Directory permissions to users and groups.

For instance, let a user Create and Update other users, let a user Modify memberships to groups in a specific OU etc.

**Comment by Hindy-UK** [comment]
@Sjark I wanted to be able to do this too. I came across this article by Joe Corey:
[https://blogs.technet.microsoft.com/joec/2013/04/25/active-directory-delegation-via-powershell/](url)

I then had a go at using this in a DSC script resource, which you can see at line 230 here:
[https://github.com/Hindy-UK/CustomScripts/blob/master/phit-azure-deployment-scripts/ActiveDirectoryProd.ps1](url)

It's one of my first attempts at that so it's a bit messy and only delegates reset password to one group on one OU. I might look into improving it after I finish my attempt at making customs resources for AD sites, subnets and site links.

**Comment by glennmate** [comment]
Being able to update permissions on an OU would be a great benefit when prestaging CNO objects for failover clustering.

**Comment by johlju** [comment]
This is being worked on in PR #186.
