### ISSUE TITLE
xADUser invalid $PSBoundParameter index for the $UserName parameter

### ISSUE THREAD

**Issue by tamas7** [PowerShell/xActiveDirectory#58]
Creating a new user will fail with:

    A parameter cannot be found that matches parameter name 'Name'.
    Index operation failed; the array index evaluated to null.

The issue is that `$PSBoundParameter` is declared for `$Name`, instead of `$UserName`, hence the failed index operation.

Changing the two occurrence of:

    $PSBoundParameters['Name'] = $Name;

to:

    $PSBoundParameters['UserName'] = $UserName;

in `DSCResources\MSFT_xADUser\MSFT_xADUser.psm1` resolves the issue.

Tested in Azure using PowerShell DSC VM extension.

Hope this helps.

**Comment by iainbrighton** [comment]
Hi @tamas7 - thanks for reporting this. I'll get it fixed. Is this on the dev branch? If so, I'm not sure how it got passed all the unit tests... :confounded:

**Comment by iainbrighton** [comment]
@tamas7 I've fixed this, added test coverage and submitted PR #59. I've actually removed that assignment as the `UserName` PSBoundParameter will always be there as it's mandatory!

@TravisEz13 @KarolKaczmarek Can we make sure this is merged before the next release is pushed to the PSGallery as the updated xADUser resource won't work without it?!

**Comment by tamas7** [comment]
@iainbrighton Thanks for the PR, tested it in Azure, works!
