### ISSUE TITLE
PSScriptAnalyzer errors need to be fixed

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/xActiveDirectory#66]
```
Thank you for contributing to the PowerShell Gallery. We have analyzed your module, xActiveDirectory 2.9.0.0 and found it contains the following issues:
RuleName	Severity	FileName	Line	Message
PSAvoidUsingUserNameAndPassWordParams	Error	MSFT_xADUser.psm1	791	Function 'Test-Password' has both username and password parameters. A credential parameter of type PSCredential with a CredentialAttribute where PSCredential comes before CredentialAttribute should be used.
PSAvoidUsingUserNameAndPassWordParams	Error	MSFT_xADUser.psm1	484	Function 'Set-TargetResource' has both username and password parameters. A credential parameter of type PSCredential with a CredentialAttribute where PSCredential comes before CredentialAttribute should be used.
PSAvoidUsingUserNameAndPassWordParams	Error	MSFT_xADUser.psm1	284	Function 'Test-TargetResource' has both username and password parameters. A credential parameter of type PSCredential with a CredentialAttribute where PSCredential comes before CredentialAttribute should be used.
PSAvoidUsingUserNameAndPassWordParams	Error	MSFT_xADUser.psm1	71	Function 'Get-TargetResource' has both username and password parameters. A credential parameter of type PSCredential with a CredentialAttribute where PSCredential comes before CredentialAttribute should be used.
These errors were generated by PowerShell Script Analyzer, which can be found at http://www.powershellgallery.com/packages/PSScriptAnalyzer/. 
```

**Comment by iainbrighton** [comment]
@KarolKaczmarek When did the PSScriptAnalyzer start kicking in?! I'll need to suppress these errors, as being able to specify a user's username and password during account creation is kinda important! :wink:

**Comment by TravisEz13** [comment]
I believe this is a PSScriptAnalyzer issue.
You may just need to add the CredentialAttribute  to the credential parameters.

The actual password is passed as a credential object.  I believe there was a reason that the user name was not passed in the credential object, but you will have to remind me.

```PowerShell
    param
    (
        [Parameter(Mandatory)]
        [System.String] $DomainName,

        [Parameter(Mandatory)]
        [System.String] $UserName,
    
        [Parameter(Mandatory)]
        [System.Management.Automation.PSCredential] $Password,
        
        [ValidateNotNull()]
        [System.Management.Automation.PSCredential] $DomainAdministratorCredential
    )
```
@raghushantha Can you help here?

**Comment by KarolKaczmarek** [comment]
@iainbrighton 
We run PSSA for repos using WMF 5 test VM since few weeks during every appveyor run. This doesn't apply to this repo, however we will eventually enable it here as well.

The error log attached is from PS Gallery team which runs PSSA for every submission and forwards results to the owner of the module. 

Why can't we use PSCredential here?

**Comment by iainbrighton** [comment]
@KarolKaczmarek Username is a currently a key and I didn't think you could have a PSCredential as a key? Any change here will be a breaking change..

**Comment by iainbrighton** [comment]
@KarolKaczmarek @TravisEz13 Any update on this? I can add the `[Diagnostics.CodeAnalysis.SuppressMessageAttribute()]` attribute to stop the PSScriptAnalyzer reporting the error but that won't solve the underlying problem..

**Comment by raghushantha** [comment]
We plan to have updates to these rules in the Feb release (week of 2/15).

Here is the gist of changes:
securestring/PSCredential (+Credential attr) type for password is ok, Having String type for Username is ok.

When using PSCredential type, supply the Credential() attribute also. Here is the reason:
https://github.com/PowerShell/PSScriptAnalyzer/issues/363

For this instance, can you suppress the rule application using -ExcludeRule parameter or using inline suppression.

**Comment by TravisEz13** [comment]
@iainbrighton, after the updated rule I believe you will be good if you add the credential attribute.  No need to suppress. @KarolKaczmarek Do we need to deal with this before the rule update?

**Comment by iainbrighton** [comment]
@TravisEz13 @KarolKaczmarek I also receive the following warnings:
```
PSUseApprovedVerbs                  Warning      MSFT_xADUs 769   The cmdlet 'Validate-Parameters' uses an unapproved
                                                 er.psm1          verb.
PSUseSingularNouns                  Warning      MSFT_xADUs 836   The cmdlet 'Get-ADCommonParameters' uses a plural
                                                 er.psm1          noun. A singular noun should be used instead.
PSUseSingularNouns                  Warning      MSFT_xADUs 769   The cmdlet 'Validate-Parameters' uses a plural noun.
                                                 er.psm1          A singular noun should be used instead.
PSDSCDscExamplesPresent             Information  MSFT_xADUs 1     No examples found for resource 'MSFT_xADUser'
                                                 er.psm1
PSDSCDscTestsPresent                Information  MSFT_xADUs 1     No tests found for resource 'MSFT_xADUser'
                                                 er.psm1
```
Do these warnings need fixing too (except the `PSDSCDscTestsPresent` one)?

The `PSUserSingularNouns` and `PSUseApprovedVerbs` aren't really a problem as they're not exported. Can I just suppress these where appropriate to stop the analyzer picking them up in the future or do you want me to rename them completely?

**Comment by TravisEz13** [comment]
@iainbrighton  I believe we only validate errors currently.

**Comment by PlagueHO** [comment]
@TravisEz13, that is correct, but there is an [enhancement being proposed](https://github.com/PowerShell/DscResource.Tests/issues/28) that will run warnings as well - but potentially only on a subset of warning rules. So it is possible that some of these issues might need to be resolved too.

**Comment by iainbrighton** [comment]
@TravisEz13 @PlagueHO I would not normally use `Validate-Parameters` as a private function name; I would name it `ValidateParameters` as it's not exported. This would resolve the above errors, but I'm not sure this meets the style guidelines?

**Comment by PlagueHO** [comment]
@iainbrighton - we have the same problem in some of the xNetworking resources. And I'm sure it's common in lots of other resources.

My thoughts are that the styleguidelines should be updated to allow for this - any non-exported function names can use unsupported Verbs if they don't have a dash in them. @TravisEz13, @tysonjhayes ?

And then we could change any non-supported functions to use names like ```ValidateParameters```.

**Comment by tysonjhayes** [comment]
Personally I have a pet peeve for non approved verbs and non dashes. So basically everything should be verb-noun with an approved verb, but this is purely IMO. :grin: 

My reasoning is purely because we have approved verbs, you get warnings for non-approved verbs when importing the module, and it maintains a readability and standards. Now we could make an arguement of if approved verbs are needed as a whole but that'll baloon quickly :laughing:

**Comment by PlagueHO** [comment]
I'm sure I could look this up or experiment with it but I'm being awfully lazy :smile:, but does PS give you warnings if non-dashed non-approved verb functions are not exported in the module? I had a feeling PSSA only throw warnings for exported function names with dashes - so I assumed (perhaps wrongly) that PS was OK without verb-noun function naming if they weren't exported.

I don't really have a preference either way, but avoiding warnings from PS or PSSA should definitely be top priority.

**Comment by iainbrighton** [comment]
@tysonjhayes @PlagueHO You only get warnings for unapproved verbs when they're exported. This I 100% agree with.

Now whether we need to use only approved verbs with non-plural nouns for internal functions should be defined in the style guidelines. IMHO I don't think it matters too much. I would much rather have an internal function name that is descriptive than having to find an approved verb.For example, I think Validate-Parameters is more descriptive of what is happening than Assert-Parameter. I can handle a change to Assert (assuming it would be the correct verb to use in this instance).

I think that if the internal functions have the hyphen removed, the PSScriptAnalyzer doesn't care report on any non-approved verbs or plural nouns making it almost a moot point!

What is evident is that there is some major inconsistencies across all repositories that needs documenting and then fixing. I'm happy to play by the rules; whatever they are.

**Comment by PlagueHO** [comment]
Right, so what we really need is someone to make an executive decision here ( @KarolKaczmarek, @tysonjhayes, @TravisEz13 I'm looking at you here :smile:) about what the rule should be and just document it in the guidelines.

-[ ] Option 1: All functions must obey verb-noun (singular) rule regardless if they are exported.
-[ ] Option 2: Non-exported functions can ignore verb-noun (singular) rule.

**Comment by iainbrighton** [comment]
@PlagueHO Does option 2 need updating to state that the hyphen should be removed? If not, they will still trip the PSSA?

__All__ Obviously there __should only ever be 3 exported functions__ from each DSC resource. I'm not sure that this should make a difference when picking an option though. I guess picking one rule that works across all repositories (DSC or not) would make the most sense?

**Comment by PlagueHO** [comment]
@iainbrighton - Doh - fixed.

**Comment by iainbrighton** [comment]
@KarolKaczmarek @TravisEz13 Can this now be closed out? I'm sure @PlagueHO has "fixed" all the PSSA errors?
