### ISSUE TITLE
Bug in xADDomainController

### ISSUE THREAD

**Issue by chlsmith** [PowerShell/xActiveDirectory#67]
On the Get-TargetResource section, the write-verbose statement calls for a $fullDomainName variable that isn't defined.

**Comment by iainbrighton** [comment]
@chlsmith Thanks for the report. Are you willing to submit a pull request to fix this? If not, I'm sure I'll get around to it :wink:

**Comment by chlsmith** [comment]
The pull request is not something I really know how to do.   I know how to clone it, make the change, and then post it back, but there are tests and things always required that I really don't know how to do.

**Comment by iainbrighton** [comment]
@chlsmith It looks like @mgreenegit has PR #68 in already for this :smile:

**Comment by mgreenegit** [comment]
Yes, chlsmith reported it to me yesterday

**Comment by GoateePFE** [comment]
I ran into this with a customer today.  No fix yet?

**Comment by PlagueHO** [comment]
@GoateePFE - it looks like a fix was made, a PR issued but was closed without being merged because their were merge conflicts weren't fixed.

I'll fix it and issue a new PR.

**Comment by PlagueHO** [comment]
I have reissued a PR to fix this:
https://github.com/PowerShell/xActiveDirectory/pull/95

**Comment by iainbrighton** [comment]
@PlagueHO @GoateePFE @mgreenegit This is inbound with the xADComputer PR..
