### ISSUE TITLE
cADGroup

### ISSUE THREAD

**Issue by adbertram** [PowerShell/xActiveDirectory#7]
I would like to develop a DSC resource for AD groups.  I've forked the repo and am beginning to work on this.  Let me know if you'd like for me to do anything else.  I'm pretty new to Github.

**Comment by GoateePFE** [comment]
Thanks. Can you test this resource over in the PowerShell.org repo pull queue?
https://github.com/PowerShellOrg/cActiveDirectory/pull/1

**Comment by adbertram** [comment]
I apologize.  I've got way too much going on right now and am going to have to renig on this. :/

**Comment by GoateePFE** [comment]
No sweat. No one wins when you (or anyone else) over commits. Good to see you draw boundaries with your time.

**Comment by irwins** [comment]
Hi guys, I also tried creating a DSC for ADGroups. Is there going to be a new one? Just wondering...

Regards,

Irwin

**Comment by iainbrighton** [comment]
There is an outstanding pull request #36 for this functionality, but only to create AD groups.

Group membership functionality will be follow shortly. Pull request #20 implements group membership but it's been decided to merge the group membership functionality into the xADGroup resource to mirror the behaviour of the built-in Group resource.

**Comment by GoateePFE** [comment]
I like that direction.  Sorry I cannot be more help.

Ashley
