### ISSUE TITLE
xADDomain: Add Exclude DNS parameter

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xActiveDirectory#74]
I know this parameter was just removed, but I'm just querying why? @iainbrighton - I've tried to track back through the issues list and PR's but can't figure out if this was removed because it didn't work properly or for another reason. I didn't see anything specific about it in the readme.md.

I have a need to be able to exclude DNS installation for child domains where the child DC's don't need a DNS of their own but instead can use the parent DNS.

This is not critical, but would love to be able to use it.

**Comment by iainbrighton** [comment]
@PlagueHO In short it was removed temporarily whilst we discussed the ins and outs over in #38.

**Comment by PlagueHO** [comment]
Ah! I missed that that. Thanks for the into - I'll close this one. No point cluttering things up.
