### ISSUE TITLE
Merge xOU module into xActiveDirectory module

### ISSUE THREAD

**Issue by vors** [PowerShell/xActiveDirectory#8]
Per discussion in https://github.com/PowerShell/DscResources/issues/11
xOU module can be found in PSGallery:

```powershell
Find-Module xOU
```

**Comment by GoateePFE** [comment]
Hello, vors.  Please proceed with this change.  It is needed and welcomed to bring these into one module.

**Comment by iainbrighton** [comment]
I'm happy to do this and write some Pester test coverage if that's wanted?

**Comment by GoateePFE** [comment]
Thank you.  Please proceed.

**Comment by iainbrighton** [comment]
@GoateePFE @vors - I have this functionality ready go once pull request #36 is merged!

**Comment by olljanat** [comment]
xOu module should be definitely merged to this module.

I also found that there is small issue on xOu module which should be also fixed:
https://gallery.technet.microsoft.com/xOU-PowerShell-Module-DSC-be133067/view/Discussions
