### ISSUE TITLE
DomainName Missing when using CreateADPDC.ps1 with ARM template

### ISSUE THREAD

**Issue by paulieguk** [PowerShell/xActiveDirectory#83]
I am working on quite an urgent project and I am trying to promote a Windows VM to a domain controller in a new domain, using the PowerShell DSC extension in the RM templates.  I am using the CreateADPDC.ps1 solution unmodified, with my own template.  When I run the deployment:
1)The package get downloaded from my external blob storage
2) Installs all the modules
3) when it goes to run it, it errors with Mandatory Parameter missing DomainName.  However if I look in the 0.settings file the domainName is there as a parameter and value, so it seems there is an issue between the content being downloaded then being passed to the CreateADPDC.ps1 script but I have no idea where.

I have attached the 0.settings file and the CreateADPDC.PS1 file in a zip.

Hopefully someone will have an idea.  Thank you in advance for your help,
Regards,
Paul

[missingDomainName.zip](https://github.com/PowerShell/xActiveDirectory/files/205963/missingDomainName.zip)

**Comment by iainbrighton** [comment]
@paulieguk Do you have a DomainName, RetryCount and RetryIntervalSec properties set? Is the problem here?
```powershell
xWaitForADDomain DscForestWait {
    DomainName = $Node.DomainName
    DomainUserCredential = $domainCred
    RetryCount = $Node.RetryCount
    RetryIntervalSec = $Node.RetryIntervalSec
    DependsOn = "[xADDomain]FirstDS"
} 
```
Should this be:
```powershell
xWaitForADDomain DscForestWait {
    DomainName = $DomainName
    DomainUserCredential = $domainCred
    RetryCount = 10
    RetryIntervalSec = 30
    DependsOn = "[xADDomain]FirstDS"
} 
```

**Comment by paulieguk** [comment]
Iain,

Thank you for your reply.  Those properties for interval count and Intervalsec are in the PS1 file, of course Domain is a parameter.  I am testing those changes (takes about 25mins).  But the file is unmodified from the original and this section happens quite late in the process and not of the preceding steps (e.g. create the disk have happened).  Fingers crossed.

Thank you,
Paul

**Comment by iainbrighton** [comment]
It will attempt to compile that configuration into a .mof file. If there's a problem it'll moan before you even start to apply it!

**Comment by iainbrighton** [comment]
@paulieguk How did you get on?

**Comment by paulieguk** [comment]
Hi Iain,



You help got me on the right track.  The main problem was I trusted the file too much, and there were a number of typos.  So the Node.$domainname you highlighted plus in addition $domaincreds was not used consistenantly, sometimes it was $domaincred  (no 's' on the end).



Thank you very much for you assistance.



Regards,

Paul

Paul Gregory
Head of Microsoft Infrastructure

QA - transforming performance through learning

Witan Court, 294 Witan Gate West, Milton Keynes, Bucks MK9 1EJ
Tel?+44 (0) 1908 206 700
Fax  +44 (0) 1908 206 701

Email    paul.gregory@qa.com<mailto:paul.gregory@qa.com>
Web      www.qa.com<http://www.qa.com/>

Blog   http://www.qa.com/about-qa/blogs/paul-gregory

Twitter  http://twitter.com/paullgregory

Youtube http://youtube.com/user/pauliegregory

________________________________

**Comment by iainbrighton** [comment]
@paulieguk Cool - where is the `CreateADPDC.ps1` file as that should be updated? Are you happy to close this issue out?

**Comment by TravisEz13** [comment]
@iainbrighton there are many copies of CreateADPDC.ps1.  

1. https://github.com/Azure/azure-quickstart-templates/blob/master/sharepoint-three-vm/dsc/CreateADPDC.ps1.zip
2. https://github.com/Azure/azure-quickstart-templates/blob/master/sharepoint-server-farm-ha/dscv2/CreateADPDC.ps1.zip
3. https://github.com/Azure/azure-quickstart-templates/blob/875d139c16c9c023dce519e6dd48c707e3473346/sql-server-2014-alwayson-dsc/CreateADPDC.ps1.zip
4. https://github.com/Azure/azure-quickstart-templates/blob/875d139c16c9c023dce519e6dd48c707e3473346/create-hpc-cluster/CreateADPDC.ps1.zip
5. https://github.com/Azure/azure-quickstart-templates/blob/3b8e5286b711b898ad47c87ab11384a1cf197957/active-directory-new-domain/CreateADPDC.ps1.zip
6. https://github.com/Azure/azure-quickstart-templates/blob/875d139c16c9c023dce519e6dd48c707e3473346/active-directory-new-domain-ha-2-dc/CreateADPDC.ps1.zip

**Comment by iainbrighton** [comment]
@TravisEz13 Why are they all .zip files? Gonna be a bit difficult to send a PR for them?

**Comment by TravisEz13** [comment]
@iainbrighton First, another team did this.  because the Azure DSC extension needs a zip file built a certain way.  So they just put it on GitHub.  My suggestion, don't fix their zip.  In some repo, build CreateADPDC.ps1.zip using AppVeyor and file an issue with them to pick up the zip from AppVeyor instead of GitHub.

**Comment by kwirkykat** [comment]
Closing this as it is external to xActiveDirectory
