### ISSUE TITLE
Packages of releases 2.10.0 & 2.11.0 are missing?

### ISSUE THREAD

**Issue by kvaes** [PowerShell/xActiveDirectory#94]
Dear Sir/Madam,

Since yesterday, the package with version 2.10.0 disappeared from the repository...

https://powershellgallery.azureedge.net/packages/xactivedirectory.2.10.0.nupkg

I noticed that there was a newer version too, so I tried that one... And no luck either.

https://powershellgallery.azureedge.net/packages/xactivedirectory.2.11.0.nupkg

When trying the previous version, this  still works...

https://powershellgallery.azureedge.net/packages/xactivedirectory.2.9.0.nupkg

Kind regards,

Karim

**Comment by PlagueHO** [comment]
Hi @kvaes, I tried the links you provided and they all seem to be available (downloads worked). Are you able re-check?

Thanks

**Comment by kvaes** [comment]
Not for me... Could it be that the packages on the "edge" are using CDN underneath and that I'm experiencing an issue with a certain node?

**Comment by PlagueHO** [comment]
It is certainly possible it is a CDN issue.

Are you able to use ```Install-Module xActiveDirectory -RequiredVersion 2.11.0.0``` or are you using WMF 4.0?

**Comment by kvaes** [comment]
I'm using Azure Automation... Where we do a lot of automated deployments. When setting up an AA (azure automation) account, we also automaticlly import the modules. A code snipplet ;

        New-AzureRmAutomationModule `
            -ResourceGroupName $ResourceGroupName `
            -AutomationAccountName $AutomationAccountName `
            -Name $ModuleName `
            -ContentLink $ActualUrl

Where the $ActualUrl will be the one we retrieved from powershellgallery and those are the ones I mentioned earlier.

So when saying this, I'm see that AA is possible to import 2.9.0, but not 2.10.0/2.11.0, which relates to my own machine not being able to retrieve the packages.

This makes my assume that the issue is related to "Europe". As I'm located in Belgium and my AA is located in "West Europe" (Amsterdam).

**Comment by PlagueHO** [comment]
I'm located in New Zealand - a long way away - and so I assume I'm probably using West US or Southeastern Australia CDN's. Are you able to try out any of the other Resources that were released today? E.g. xNetworking v2.9.0.0?

This URL:
https://powershellgallery.azureedge.net/packages/xNetworking.2.9.0.0.nupkg
Does not work for me, but I would expect it to.

How to you retrieve the $ActualUrl from PSGallery - I did some messing about with Find-Module and couldn't locate a URL that was a direct link to the nuget package.

**Comment by PlagueHO** [comment]
I just noticed that these are all stored as Azure blobs, so it very well take some time for replication, although I would have expected xActiveDirectory v2.10.0.0 to be available by now as that was published some time back.

**Comment by kvaes** [comment]
The full code we use (including the lookup)

```
# Requires that authentication to Azure is already established before running
# Obtained from Joe Levy 

param(
    [Parameter(Mandatory=$true)]
    [String] $ResourceGroupName,

    [Parameter(Mandatory=$true)]
    [String] $AutomationAccountName,
    
    [Parameter(Mandatory=$true)]
    [String] $ModuleName,

    # if not specified latest version will be imported
    [Parameter(Mandatory=$false)]
    [String] $ModuleVersion
)

$Url = "https://www.powershellgallery.com/api/v2/Search()?`$filter=IsLatestVersion&searchTerm=%27$ModuleName $ModuleVersion%27&targetFramework=%27%27&includePrerelease=false&`$skip=0&`$top=40" 
$SearchResult = Invoke-RestMethod -Method Get -Uri $Url -UseBasicParsing

if(!$SearchResult) {
    Write-Error "Could not find module '$ModuleName' on PowerShell Gallery."
}
elseif($SearchResult.C -and $SearchResult.Length -gt 1) {
    Write-Error "Module name '$ModuleName' returned multiple results. Please specify an exact module name."
}
else {
    $PackageDetails = Invoke-RestMethod -Method Get -UseBasicParsing -Uri $SearchResult.id 
    
    if(!$ModuleVersion) {
        $ModuleVersion = $PackageDetails.entry.properties.version
    }

    $ModuleContentUrl = "https://www.powershellgallery.com/api/v2/package/$ModuleName/$ModuleVersion"

    # Test if the module/version combination exists
    try {
        Invoke-RestMethod $ModuleContentUrl -ErrorAction Stop | Out-Null
        $Stop = $False
    }
    catch {
        Write-Error "Module with name '$ModuleName' of version '$ModuleVersion' does not exist. Are you sure the version specified is correct?"
        $Stop = $True
    }

    if(!$Stop) {

        # Find the actual blob storage location of the module
        do {
            $ActualUrl = $ModuleContentUrl
            $ModuleContentUrl = (Invoke-WebRequest -Uri $ModuleContentUrl -MaximumRedirection 0 -ErrorAction Ignore).Headers.Location 
        } while($ModuleContentUrl -ne $Null)

        New-AzureRmAutomationModule `
            -ResourceGroupName $ResourceGroupName `
            -AutomationAccountName $AutomationAccountName `
            -Name $ModuleName `
            -ContentLink $ActualUrl
    }
}
```

**Comment by PlagueHO** [comment]
Oh I see! 

The xNetworking resource is here:
https://powershellgallery.azureedge.net/packages/xnetworking.2.9.0.nupkg
I can download it just fine - can you check it from your side?

I just found out the blob name is case sensitive. Could you possibly try downloading the file using a US proxy service to see if it is indeed a delay with the CDN's?

**Comment by kvaes** [comment]
It appears to be working again... A glitch in the system I guess?

**Comment by PlagueHO** [comment]
My guess would be a delay in the blobs propagating between data centers.

Are we able to close this one?

**Comment by kvaes** [comment]
Issue closed
